import assert from "node:assert/strict";
import test from "node:test";
import type { ModelAdapter } from "@relay/contracts";
import { Orchestrator } from "@relay/orchestrator";
import { ToolRunner } from "@relay/tool-runner";
import { WorkflowEngine } from "../src/index.js";

test("planner-reviewer jobs checkpoint and create an artifact",async()=>{const adapter:ModelAdapter={id:"demo:relay",provider:"demo",model:"worker",capabilities:{tools:true,structuredOutput:true,streaming:false,selfHosted:true},estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0,supports:()=>true,invoke:async(request)=>({provider:"demo",model:"worker",outputText:`answer-${request.messages.length}`,traceId:"provider"})};const orchestrator=new Orchestrator([adapter],new ToolRunner());const engine=new WorkflowEngine(orchestrator,orchestrator.store);const job=await engine.submit("tenant","actor","planner-reviewer",{objective:"Build a test",priority:"private"});await engine.execute(job.id);const completed=await orchestrator.store.job(job.id);assert.equal(completed?.status,"succeeded");assert.equal((await orchestrator.store.listArtifacts("tenant",job.id)).length,1);});

test("startup recovery claims and completes queued jobs exactly once",async()=>{let invocations=0;const adapter:ModelAdapter={id:"demo:relay",provider:"demo",model:"worker",capabilities:{tools:true,structuredOutput:true,streaming:false,selfHosted:true},estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0,supports:()=>true,invoke:async()=>{invocations+=1;return{provider:"demo",model:"worker",outputText:"recovered",traceId:"provider"};}};const orchestrator=new Orchestrator([adapter],new ToolRunner());const queued=await orchestrator.store.createJob({tenantId:"tenant",actorId:"actor",type:"single",input:{objective:"Recover this",priority:"private"}});const engine=new WorkflowEngine(orchestrator,orchestrator.store);await Promise.all([engine.recoverAll(),engine.recoverAll()]);assert.equal((await orchestrator.store.job(queued.id))?.status,"succeeded");assert.equal(invocations,1);});

test("adhoc workflows execute ordered model-pinned steps",async()=>{const calls:string[]=[];const adapter:ModelAdapter={id:"demo:relay",provider:"demo",model:"worker",capabilities:{tools:true,structuredOutput:true,streaming:false,selfHosted:true},estimatedInputCostPerMillion:0,estimatedOutputCostPerMillion:0,supports:()=>true,invoke:async(request)=>{const content=String(request.messages.at(-1)?.content);calls.push(content);return{provider:"demo",model:"worker",outputText:`result-${calls.length}`,traceId:"provider"};}};const orchestrator=new Orchestrator([adapter],new ToolRunner());const engine=new WorkflowEngine(orchestrator,orchestrator.store);const job=await engine.submit("tenant","actor","adhoc",{objective:"Compare options",priority:"private",steps:[{id:"a",name:"Query",prompt:"Collect facts",modelHint:"demo:relay"},{id:"b",name:"Synthesize",prompt:"Write the answer",modelHint:"demo:relay"}]});await engine.execute(job.id);const completed=await orchestrator.store.job(job.id);assert.equal(completed?.status,"succeeded");assert.equal(completed?.state.stage,"completed step 2 of 2");assert.equal(completed?.state.currentStepId,"");assert.equal(calls.length,2);assert.match(calls[1],/result-1/);assert.equal((completed?.result as {output:string}).output,"result-2");const audit=await orchestrator.store.listAudit("tenant");assert.ok(audit.some(event=>event.action==="artifact.created"&&event.resourceType==="artifact"));});
