import { randomUUID } from "node:crypto";
import type { AdapterStreamEvent, ChatRequest, ChatResult, ModelAdapter, ToolCall } from "@relay/contracts";
import { parseSse, providerFetch, providerResponse, textContent } from "../shared.js";

type Config={id:string;model:string;apiKey:string;baseUrl:string;inputCostPerMillion:number;outputCostPerMillion:number;reasoningEffort?:string};
export class OpenAIResponsesAdapter implements ModelAdapter {
  readonly provider="openai" as const; readonly capabilities={tools:true,structuredOutput:true,streaming:true,selfHosted:false};
  readonly id:string; readonly model:string; readonly estimatedInputCostPerMillion:number; readonly estimatedOutputCostPerMillion:number;
  constructor(private readonly config:Config){this.id=config.id;this.model=config.model;this.estimatedInputCostPerMillion=config.inputCostPerMillion;this.estimatedOutputCostPerMillion=config.outputCostPerMillion;}
  supports():boolean{return Boolean(this.config.apiKey);}
  private input(request:ChatRequest):unknown[]{const result:unknown[]=[]; for(const message of request.messages){if(message.toolCalls?.length){for(const call of message.toolCalls)result.push({type:"function_call",call_id:call.id,name:call.name,arguments:JSON.stringify(call.arguments)});continue;} if(message.role==="tool"){result.push({type:"function_call_output",call_id:message.toolCallId,output:textContent(message.content)});continue;} result.push({role:message.role==="system"?"developer":message.role,content:textContent(message.content)});} return result;}
  private payload(request:ChatRequest,stream=false){return{model:this.model,input:this.input(request),stream,reasoning:this.config.reasoningEffort?{effort:this.config.reasoningEffort}:undefined,tools:request.tools?.map(t=>({type:"function",name:t.name,description:t.description,parameters:t.inputSchema,strict:true})),text:request.responseSchema?{format:{type:"json_schema",name:"response",strict:true,schema:request.responseSchema}}:undefined};}
  private parse(body:any):ChatResult{const calls:ToolCall[]=(body.output??[]).filter((i:any)=>i.type==="function_call").map((i:any)=>({id:i.call_id,name:i.name,arguments:typeof i.arguments==="string"?JSON.parse(i.arguments||"{}"):i.arguments})); const outputText=body.output_text??(body.output??[]).flatMap((i:any)=>i.content??[]).filter((c:any)=>c.type==="output_text").map((c:any)=>c.text).join(""); const usage={inputTokens:body.usage?.input_tokens,outputTokens:body.usage?.output_tokens}; return{provider:"openai",model:body.model??this.model,outputText:outputText||undefined,toolCalls:calls.length?calls:undefined,usage:{...usage,costUsd:((usage.inputTokens??0)*this.estimatedInputCostPerMillion+(usage.outputTokens??0)*this.estimatedOutputCostPerMillion)/1_000_000},traceId:randomUUID()};}
  async invoke(request:ChatRequest):Promise<ChatResult>{const body=await providerFetch(`${this.config.baseUrl.replace(/\/$/,"")}/responses`,{method:"POST",headers:{authorization:`Bearer ${this.config.apiKey}`,"content-type":"application/json"},body:JSON.stringify(this.payload(request))}) as any; return this.parse(body);}
  async *invokeStream(request:ChatRequest):AsyncGenerator<AdapterStreamEvent>{const response=await providerResponse(`${this.config.baseUrl.replace(/\/$/,"")}/responses`,{method:"POST",headers:{authorization:`Bearer ${this.config.apiKey}`,"content-type":"application/json"},body:JSON.stringify(this.payload(request,true))}); let completed:any; for await(const frame of parseSse(response)){if(frame.data==="[DONE]")continue; const event=JSON.parse(frame.data); if(event.type==="response.output_text.delta"&&event.delta)yield{type:"delta",text:event.delta}; if(event.type==="response.completed")completed=event.response;} if(!completed)throw new Error("OpenAI stream ended without a completed response"); yield{type:"result",result:this.parse(completed)};}
  async health(){const started=performance.now();try{await providerFetch(`${this.config.baseUrl.replace(/\/$/,"")}/models`,{headers:{authorization:`Bearer ${this.config.apiKey}`}},15_000);return{ok:true,latencyMs:performance.now()-started};}catch(error){return{ok:false,latencyMs:performance.now()-started,error:error instanceof Error?error.message:"Health check failed"};}}
}
