import { useCallback, useEffect, useRef, useState } from "react";
import { Activity, ArrowUp, Bot, Boxes, Braces, Check, ChevronDown, CircleDollarSign, ClipboardCheck, Clock3, Command, FileCode2, FlaskConical, Gauge, GitBranch, GripVertical, History, KeyRound, LogOut, Menu, MessageSquare, Network, PanelLeft, PanelRight, Paperclip, Play, Plus, RotateCcw, ShieldCheck, Sparkles, Trash2, Workflow, X } from "lucide-react";
import * as api from "./api";

type View = "Chat" | "Sessions" | "Traces" | "Approvals" | "Workflows" | "Agents" | "Prompts" | "Evals" | "Usage" | "Models" | "Policies";
const nav: Array<{ label: View; icon: typeof MessageSquare }> = [
  { label: "Chat", icon: MessageSquare }, { label: "Sessions", icon: History }, { label: "Traces", icon: Activity }, { label: "Approvals", icon: ClipboardCheck }, { label: "Workflows", icon: Workflow }, { label: "Agents", icon: GitBranch }, { label: "Prompts", icon: FileCode2 }, { label: "Evals", icon: FlaskConical }, { label: "Usage", icon: Gauge }, { label: "Models", icon: Boxes }, { label: "Policies", icon: ShieldCheck }
];
const starterPrompts = ["Summarize this week's platform activity", "Check incident ABC-123 and assess impact", "Explain why this request was routed"];
const newId = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}`;
const storedBoolean = (key: string, fallback: boolean) => { try { const value = globalThis.localStorage?.getItem(key); return value === null ? fallback : value === "true"; } catch { return fallback; } };
const chatErrorMessage = (error: unknown) => { const message = error instanceof Error ? error.message : "Unknown error"; if (/Provider returned 429|provider rate limit/i.test(message)) return "OpenAI is temporarily rate-limiting this model. Wait a moment and try again, or choose another route."; if (/rate limit exceeded|too many write requests/i.test(message)) return "Relay's request limit was reached. Wait a moment and try again."; if (/insufficient_quota/i.test(message)) return "OpenAI reports that this project has no available quota. Check the API project's billing and limits."; return `Relay couldn't complete that request. ${message}`; };

export function App() {
  const [actor, setActor] = useState<api.Principal | null>();
  const [view, setView] = useState<View>("Chat"), [messages, setMessages] = useState<api.Message[]>([]), [input, setInput] = useState(""), [priority, setPriority] = useState("balanced"), [route, setRoute] = useState<api.Route | null>(null), [sending, setSending] = useState(false), [attaching, setAttaching] = useState(false);
  const [traces, setTraces] = useState<api.Trace[]>([]), [usage, setUsage] = useState<api.Usage>({ requests: 0, inputTokens: 0, outputTokens: 0, costUsd: 0 }), [sessions, setSessions] = useState<api.Session[]>([]), [approvals, setApprovals] = useState<api.Approval[]>([]), [jobs, setJobs] = useState<api.Job[]>([]), [prompts, setPrompts] = useState<api.Prompt[]>([]), [providers, setProviders] = useState<api.ProviderStatus[]>([]), [audit, setAudit] = useState<api.AuditEvent[]>([]), [policy, setPolicy] = useState<api.Policy | null>(null), [agents, setAgents] = useState<api.Agent[]>([]), [evals, setEvals] = useState<api.EvalReport[]>([]), [attachment, setAttachment] = useState<api.Artifact | null>(null);
  const [inspector, setInspector] = useState(() => storedBoolean("relay.inspector.open", true)), [navCollapsed, setNavCollapsed] = useState(() => storedBoolean("relay.sidebar.collapsed", false)), [mobileNav, setMobileNav] = useState(false), [notice, setNotice] = useState("");
  const sessionId = useRef<string>(newId()), bottom = useRef<HTMLDivElement>(null);

  const refresh = useCallback(async () => { if (!api.currentPrincipal()) return; const settled = await Promise.allSettled([api.getTraces(), api.getUsage(), api.getSessions(), api.getApprovals(), api.getJobs(), api.getPrompts(), api.getProviders(), api.getAudit(), api.getPolicy(), api.getAgents(), api.getEvals()]); if(settled[0].status==="fulfilled")setTraces(settled[0].value);if(settled[1].status==="fulfilled")setUsage(settled[1].value);if(settled[2].status==="fulfilled")setSessions(settled[2].value);if(settled[3].status==="fulfilled")setApprovals(settled[3].value);if(settled[4].status==="fulfilled")setJobs(settled[4].value);if(settled[5].status==="fulfilled")setPrompts(settled[5].value);if(settled[6].status==="fulfilled")setProviders(settled[6].value.providers);if(settled[7].status==="fulfilled")setAudit(settled[7].value);if(settled[8].status==="fulfilled")setPolicy(settled[8].value);if(settled[9].status==="fulfilled")setAgents(settled[9].value);if(settled[10].status==="fulfilled")setEvals(settled[10].value); }, []);
  useEffect(() => { api.me().then((value) => { setActor(value); void refresh(); }).catch(() => setActor(null)); }, [refresh]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);
  useEffect(() => { if (!actor) return; const id = window.setInterval(() => void refresh(), 5000); return () => clearInterval(id); }, [actor, refresh]);
  useEffect(() => { try { globalThis.localStorage?.setItem("relay.sidebar.collapsed", String(navCollapsed)); } catch { /* layout preference remains ephemeral */ } }, [navCollapsed]);
  useEffect(() => { try { globalThis.localStorage?.setItem("relay.inspector.open", String(inspector)); } catch { /* layout preference remains ephemeral */ } }, [inspector]);

  async function send(value = input, selectedAgentId = "", selectedModel = "") { const text = value.trim(); if ((!text && !attachment) || sending || attaching) return; const modelText=attachment?`${text}\n\nAttached file ${attachment.name}:\n${String(attachment.content)}`:text,visibleText=attachment?`${text}\n\n📎 ${attachment.name}`:text;setInput("");setAttachment(null);setRoute(null); setSending(true); setMessages((current) => [...current, { role: "user", content: visibleText }, { role: "assistant", content: "" }]); try { await api.streamChat(sessionId.current, modelText, priority, selectedAgentId||undefined, selectedModel||undefined, { route: setRoute, delta: (delta) => setMessages((current) => current.map((message, index) => index === current.length - 1 ? { ...message, content: String(message.content) + delta } : message)), approval: () => { setNotice("This run is waiting for a human approval."); setView("Approvals"); } }); await refresh(); } catch (error) { setMessages((current) => current.map((message, index) => index === current.length - 1 ? { ...message, content: chatErrorMessage(error), meta: "error" } : message)); } finally { setSending(false); } }
  async function attachFile(file: File) { if(file.size>750_000){setNotice("Files must be 750 KB or smaller.");return;}setAttaching(true);try{const content=await file.text();const artifact=await api.uploadArtifact(sessionId.current,file.name,file.type||"text/plain",content);setAttachment(artifact);setNotice("");}catch(error){setNotice(error instanceof Error?`Attachment failed: ${error.message}`:"Attachment upload failed.");}finally{setAttaching(false);} }
  async function openSession(id: string) { const saved = await api.getSession(id); sessionId.current = id; setMessages(saved.messages); setRoute(null); setView("Chat"); }
  if (actor === undefined) return <div className="auth-shell"><div className="auth-card"><div className="orb"><Command size={24}/></div><h2>Starting Relay</h2><p>Checking your workspace and control plane.</p></div></div>;
  if (!actor) return <AuthScreen onReady={(value) => { setActor(value); void refresh(); }}/>; 
  const pending = approvals.filter((item) => item.status === "pending").length;
  const showInspector = view === "Chat" && inspector;
  return <div className={`shell ${navCollapsed ? "nav-collapsed" : ""} ${showInspector ? "with-inspector" : ""}`}>
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}><div className="brand"><div className="brand-mark"><Command size={18}/></div><span>relay</span><button className="mobile-close" onClick={() => setMobileNav(false)}><X size={18}/></button></div><button className="new-chat" onClick={() => { sessionId.current = newId(); setMessages([]); setRoute(null); setView("Chat"); }}><Plus size={16}/> New session</button><nav>{nav.map(({ label, icon: Icon }) => <button key={label} className={view === label ? "active" : ""} onClick={() => { setView(label); setMobileNav(false); void refresh(); }}><Icon size={17}/><span>{label}</span>{label === "Approvals" && pending > 0 && <em>{pending}</em>}</button>)}</nav><div className="sidebar-spacer"/><div className="system-card"><div><span className="pulse"/>Control plane online</div><small>{providers.filter((item) => item.health?.ok).length} model routes healthy</small></div><button className="profile" onClick={() => { api.logout(); setActor(null); }}><div className="avatar">{actor.email.slice(0, 2).toUpperCase()}</div><div><strong>{actor.role}</strong><span>{actor.email}</span></div><LogOut size={16}/></button></aside>
    <main className="main"><header><button className="mobile-menu" onClick={() => setMobileNav(true)}><Menu size={19}/></button><button className="icon-button desktop-nav-toggle" aria-label={navCollapsed ? "Expand navigation" : "Collapse navigation"} title={navCollapsed ? "Expand navigation" : "Collapse navigation"} onClick={() => setNavCollapsed(!navCollapsed)}><PanelLeft size={18}/></button><div><span className="eyebrow">{actor.tenantId.slice(0, 8)} / {actor.role}</span><h1>{view}</h1></div><div className="header-actions"><span className="environment"><i/> Live</span>{view === "Chat" && <button className="icon-button" aria-label={inspector ? "Collapse run inspector" : "Expand run inspector"} title={inspector ? "Collapse run inspector" : "Expand run inspector"} onClick={() => setInspector(!inspector)}><PanelRight size={18}/></button>}</div></header>{notice && <button className="notice" onClick={() => setNotice("")}>{notice}<X size={14}/></button>}
      {view === "Chat" && <ChatView messages={messages} input={input} setInput={setInput} send={send} sending={sending} priority={priority} setPriority={setPriority} route={route} attachment={attachment} attach={attachFile} clearAttachment={()=>setAttachment(null)} bottomRef={bottom}/>} {view === "Sessions" && <SessionsView sessions={sessions} open={openSession}/>} {view === "Traces" && <TracesView traces={traces} refresh={refresh}/>} {view === "Approvals" && <ApprovalsView approvals={approvals} refresh={refresh}/>} {view === "Workflows" && <WorkflowsView jobs={jobs} refresh={refresh}/>} {view === "Agents" && <AgentsView agents={agents}/>} {view === "Prompts" && <PromptsView prompts={prompts} refresh={refresh}/>} {view === "Evals" && <EvalsView reports={evals} refresh={refresh}/>} {view === "Usage" && <UsageView usage={usage} traces={traces} policy={policy}/>} {view === "Models" && <ModelsView providers={providers}/>} {view === "Policies" && <PoliciesView audit={audit} policy={policy}/>}
    </main>{showInspector && <Inspector route={route} traces={traces} usage={usage}/>}</div>;
}

function AuthScreen({ onReady }: { onReady: (actor: api.Principal) => void }) { const [mode, setMode] = useState<"login" | "bootstrap">("login"), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [name, setName] = useState(""), [tenant, setTenant] = useState(""), [error, setError] = useState(""); const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); try { const result = mode === "login" ? await api.login(email, password) : await api.bootstrap(email, password, name, tenant); onReady(result.principal); } catch (cause) { setError(cause instanceof Error ? cause.message : "Authentication failed"); } }; return <div className="auth-shell"><form className="auth-card" onSubmit={submit}><div className="brand auth-brand"><div className="brand-mark"><Command size={18}/></div><span>relay</span></div><span className="eyebrow">SECURE CONTROL PLANE</span><h2>{mode === "login" ? "Sign in" : "Create the first workspace"}</h2><p>{mode === "login" ? "Use your Relay account." : "Bootstrap is available only while no account exists."}</p>{mode === "bootstrap" && <><label>Name<input value={name} onChange={(e) => setName(e.target.value)} required/></label><label>Workspace<input value={tenant} onChange={(e) => setTenant(e.target.value)} required/></label></>}<label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/></label><label>Password<input type="password" minLength={12} value={password} onChange={(e) => setPassword(e.target.value)} required/></label>{error && <div className="form-error">{error}</div>}<button className="primary" type="submit">{mode === "login" ? "Sign in" : "Create workspace"}</button><button className="text-button" type="button" onClick={() => setMode(mode === "login" ? "bootstrap" : "login")}>{mode === "login" ? "First run? Bootstrap Relay" : "Already initialized? Sign in"}</button></form></div>; }

function ChatView(props: { messages: api.Message[]; input: string; setInput: (v: string) => void; send: (v?: string,agentId?:string,modelHint?:string) => void; sending: boolean; priority: string; setPriority: (v: string) => void; route: api.Route | null; attachment:api.Artifact|null;attach:(file:File)=>Promise<void>;clearAttachment:()=>void;bottomRef:React.RefObject<HTMLDivElement|null> }) {
  const fileRef=useRef<HTMLInputElement>(null);
  const [agents,setAgents]=useState<api.Agent[]>([]),[providers,setProviders]=useState<api.ProviderStatus[]>([]),[selectedAgent,setSelectedAgent]=useState(""),[selectedModel,setSelectedModel]=useState("");
  useEffect(()=>{void Promise.allSettled([api.getAgents(),api.getProviders()]).then(([agentResult,providerResult])=>{if(agentResult.status==="fulfilled")setAgents(agentResult.value);if(providerResult.status==="fulfilled")setProviders(providerResult.value.providers);});},[]);
  const chooseAgent=(id:string)=>{setSelectedAgent(id);const agent=agents.find(item=>item.id===id);if(agent)props.setPriority(agent.priority);};
  const modelOptions=[{value:"",label:"Auto model"},...providers.filter(item=>item.configured&&item.model&&item.capabilities).map(item=>({value:item.id,label:String(item.model)}))];
  return <section className="chat-page">
    <div className="conversation">{props.messages.length === 0 ? <div className="empty-state"><div className="orb"><Sparkles size={25}/></div><span className="eyebrow">GOVERNED AI WORKSPACE</span><h2>What are we solving today?</h2><p>Every request is routed by policy, traced end-to-end, and visible to your team.</p><div className="starters">{starterPrompts.map((prompt) => <button key={prompt} onClick={() => props.send(prompt,selectedAgent,selectedModel)}><ArrowUp size={15}/><span>{prompt}</span></button>)}</div></div> : <div className="message-list">{props.messages.map((message, index) => <div className={`message ${message.role}`} key={index}><div className="message-avatar">{message.role === "user" ? "YOU" : <Command size={16}/>}</div><div><div className="message-head"><strong>{message.role === "user" ? "You" : "Relay"}</strong><span>{message.role === "assistant" && props.route ? `${props.route.provider} · ${props.route.model}` : "just now"}</span></div><div className={`bubble ${!message.content && props.sending ? "typing" : ""} ${message.meta === "error" ? "error-bubble" : ""}`}>{String(message.content ?? "") || <><i/><i/><i/></>}</div></div></div>)}<div ref={props.bottomRef}/></div>}</div>
    <div className="composer-wrap"><div className="composer">
      {props.attachment&&<div className="attachment-row"><div className="attachment-chip" title={props.attachment.name}><Paperclip size={13}/><span>{props.attachment.name}</span><button type="button" aria-label={`Remove ${props.attachment.name}`} onClick={props.clearAttachment}><X size={12}/></button></div></div>}
      <textarea value={props.input} onChange={(e) => props.setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); props.send(undefined,selectedAgent,selectedModel); } }} placeholder="Ask Relay anything…" rows={1}/>
      <div className="composer-bar"><div className="composer-tools"><input ref={fileRef} type="file" hidden accept="text/*,.md,.json,.csv" onChange={(e)=>{const file=e.target.files?.[0];if(file)void props.attach(file);e.target.value="";}}/><button type="button" className="tool-button" aria-label="Attach a text file" title="Attach a text file" onClick={()=>fileRef.current?.click()}><Paperclip size={15}/></button><SelectMenu ariaLabel="Select agent" value={selectedAgent} onChange={chooseAgent} placement="up" icon={Bot} options={[{value:"",label:"Relay"},...agents.map(agent=>({value:agent.id,label:agent.name}))]}/><SelectMenu ariaLabel="Preferred model" value={selectedModel} onChange={setSelectedModel} placement="up" icon={Boxes} options={modelOptions}/><SelectMenu ariaLabel="Routing priority" value={props.priority} onChange={props.setPriority} placement="up" icon={Network} options={[{value:"fast",label:"Fast"},{value:"balanced",label:"Balanced"},{value:"deep",label:"Deep"},{value:"private",label:"Private"}]}/></div><button className="send" aria-label="Send message" disabled={(!props.input.trim()&&!props.attachment) || props.sending} onClick={() => props.send(undefined,selectedAgent,selectedModel)}><ArrowUp size={18}/></button></div>
    </div></div>
  </section>;
}

function Inspector({ route, traces, usage }: { route: api.Route | null; traces: api.Trace[]; usage: api.Usage }) { const latest = traces[0]; return <aside className="inspector"><div className="inspector-title"><div><span className="eyebrow">LIVE CONTEXT</span><h3>Run inspector</h3></div><span className="live-dot"/></div><div className="inspect-section"><label>ROUTE</label>{route ? <div className="route-card"><div className="provider-icon"><Bot size={18}/></div><div><strong>{route.model}</strong><span>{route.provider} · policy selected</span></div><Check size={17}/></div> : <div className="muted-card">Send a message to inspect its route.</div>}</div><div className="inspect-section"><label>POLICY CHECKS</label>{["Tenant allowlist", "Budget available", "Tool permissions", "Data boundary"].map((item) => <div className="check-row" key={item}><span><Check size={12}/></span>{item}<small>passed</small></div>)}</div><div className="inspect-section"><label>LATEST TRACE</label>{latest ? <div className="timeline">{latest.spans.map((span) => <div className="timeline-row" key={span.id}><i/><div><strong>{span.name}</strong><span>{span.kind}</span></div><em>{span.durationMs?.toFixed(0) ?? 0}ms</em></div>)}</div> : <div className="muted-card">No spans captured yet.</div>}</div><div className="inspect-section metrics"><div><span>Requests</span><strong>{usage.requests}</strong></div><div><span>Tokens</span><strong>{(usage.inputTokens + usage.outputTokens).toLocaleString()}</strong></div><div><span>Spend</span><strong>${usage.costUsd.toFixed(3)}</strong></div></div></aside>; }
function Page({ title, subtitle, children, action }: { title: string; subtitle: string; children: React.ReactNode; action?: React.ReactNode }) { return <section className="page"><div className="page-title"><div><span className="eyebrow">CONTROL PLANE</span><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>{children}</section>; }
function Empty({ icon: Icon, text }: { icon: typeof Activity; text: string }) { return <div className="empty-table"><Icon size={22}/><span>{text}</span></div>; }
function SelectMenu({ value, onChange, options, ariaLabel, placement = "down", icon: Icon }: { value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }>; ariaLabel: string; placement?: "up" | "down"; icon?: typeof Network }) {
  const [open, setOpen] = useState(false), root = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: PointerEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("pointerdown", close); document.addEventListener("keydown", escape); return () => { document.removeEventListener("pointerdown", close); document.removeEventListener("keydown", escape); }; }, []);
  const selected = options.find((option) => option.value === value) ?? options[0];
  return <div className={`custom-select ${placement}`} ref={root}><button type="button" className="select-trigger" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen(!open)}>{Icon && <Icon size={15}/>}<span>{selected?.label}</span><ChevronDown size={14}/></button>{open && <div className="select-menu" role="listbox" aria-label={ariaLabel}>{options.map((option) => <button type="button" role="option" aria-selected={option.value === value} className={option.value === value ? "selected" : ""} key={option.value} onClick={() => { onChange(option.value); setOpen(false); }}><span>{option.label}</span>{option.value === value && <Check size={13}/>}</button>)}</div>}</div>;
}
function SessionsView({ sessions, open }: { sessions: api.Session[]; open: (id: string) => void }) { return <Page title="Session history" subtitle="Durable conversations scoped to this tenant."><div className="list-card">{sessions.length ? sessions.map((session) => <button className="list-row" key={session.id} onClick={() => open(session.id)}><MessageSquare size={18}/><div><strong>{String(session.messages.find((m) => m.role === "user")?.content ?? "New session").slice(0, 90)}</strong><span>{session.messages.length} messages · {new Date(session.updatedAt).toLocaleString()}</span></div><code>{session.id.slice(0, 8)}</code></button>) : <Empty icon={History} text="No persisted sessions yet."/>}</div></Page>; }
function TracesView({ traces,refresh }: { traces: api.Trace[];refresh:()=>Promise<void> }) { const [replaying,setReplaying]=useState("");return <Page title="Execution traces" subtitle="Every model, policy, and tool operation in one timeline."><div className="table-card"><div className="table-head"><span>TRACE</span><span>SESSION</span><span>SPAN GRAPH</span><span>STATUS</span><span aria-label="Actions"/><span>STARTED</span></div>{traces.length ? traces.map((trace) => <div className="table-row" key={trace.id}><code>{trace.id.slice(0, 8)}</code><span>{trace.sessionId.slice(0, 8)}</span><div className="span-pills">{trace.spans.map((span) => <i title={span.name} className={span.kind} key={span.id}/>)}</div><span className={`status ${trace.status}`}><i/>{trace.status}</span><button className="icon-button replay" title="Replay trace" disabled={replaying===trace.id} onClick={async()=>{setReplaying(trace.id);try{await api.replayTrace(trace.id);await refresh();}finally{setReplaying("");}}}><RotateCcw size={13}/></button><time>{new Date(trace.startedAt).toLocaleTimeString()}</time></div>) : <Empty icon={Activity} text="Traces appear after your first request."/>}</div></Page>; }
function ApprovalsView({ approvals, refresh }: { approvals: api.Approval[]; refresh: () => Promise<void> }) { const resolve = async (item: api.Approval, status: "approved" | "rejected") => { await api.resolveApproval(item.id, status); await refresh(); }; return <Page title="Human approvals" subtitle="Review every proposed side effect before execution."><div className="list-card">{approvals.length ? approvals.map((item) => <div className="approval-row" key={item.id}><div className="provider-icon"><KeyRound size={17}/></div><div><strong>{item.toolName}</strong><span>{new Date(item.requestedAt).toLocaleString()}</span><pre>{JSON.stringify(item.input, null, 2)}</pre></div><span className={`status ${item.status}`}>{item.status}</span>{item.status === "pending" && <div className="row-actions"><button className="danger" onClick={() => void resolve(item, "rejected")}>Reject</button><button className="primary compact" onClick={() => void resolve(item, "approved")}>Approve</button></div>}</div>) : <Empty icon={ClipboardCheck} text="No approval requests."/>}</div></Page>; }
const workflowTemplates = [
  { name: "Query", prompt: "Gather the facts, requirements, and constraints needed to answer the objective." },
  { name: "Analyze", prompt: "Analyze the available material. Identify patterns, tradeoffs, risks, and missing information." },
  { name: "Challenge", prompt: "Challenge the previous output. Find unsupported assumptions, errors, and stronger alternatives." },
  { name: "Synthesize", prompt: "Produce a concise final answer that integrates the strongest findings and clearly states limitations." }
];

function WorkflowsView({ jobs, refresh }: { jobs: api.Job[]; refresh: () => Promise<void> }) {
  const makeStep=(template:typeof workflowTemplates[number]):api.WorkflowStep=>({id:newId(),...template});
  const [objective,setObjective]=useState(""),[steps,setSteps]=useState<api.WorkflowStep[]>(()=>[makeStep(workflowTemplates[0]),makeStep(workflowTemplates[3])]),[providers,setProviders]=useState<api.ProviderStatus[]>([]),[running,setRunning]=useState(false),[error,setError]=useState("");
  useEffect(()=>{void api.getProviders().then(value=>setProviders(value.providers)).catch(()=>setProviders([]));},[]);
  const modelOptions=[{value:"",label:"Auto model"},...providers.filter(item=>item.configured&&item.model&&item.capabilities).map(item=>({value:item.id,label:String(item.model)}))];
  const addTemplate=(raw:string)=>{try{const template=JSON.parse(raw) as typeof workflowTemplates[number];if(template.name&&template.prompt)setSteps(current=>[...current,makeStep(template)]);}catch{/* ignore foreign drag payloads */}};
  const reorder=(sourceId:string,targetId:string)=>setSteps(current=>{const from=current.findIndex(item=>item.id===sourceId),to=current.findIndex(item=>item.id===targetId);if(from<0||to<0||from===to)return current;const next=[...current],[moved]=next.splice(from,1);next.splice(to,0,moved);return next;});
  const run=async()=>{if(!objective.trim()){setError("Add a workflow objective.");return;}if(!steps.length){setError("Drop at least one step onto the canvas.");return;}setRunning(true);setError("");try{await api.createAdhocJob(objective.trim(),steps);await refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Workflow could not start.");}finally{setRunning(false);}};
  return <Page title="Workflow builder" subtitle="Drag steps into an ordered pipeline, assign models, and run a recoverable ad-hoc query.">
    <div className="workflow-builder">
      <aside className="workflow-palette"><span className="eyebrow">STEP LIBRARY</span><p>Drag a step onto the canvas.</p>{workflowTemplates.map(template=><button draggable key={template.name} onDragStart={event=>{event.dataTransfer.effectAllowed="copy";event.dataTransfer.setData("application/relay-template",JSON.stringify(template));}} onClick={()=>setSteps(current=>[...current,makeStep(template)])}><GripVertical size={15}/><div><strong>{template.name}</strong><span>{template.prompt}</span></div></button>)}</aside>
      <section className="workflow-canvas" onDragOver={event=>{if(event.dataTransfer.types.includes("application/relay-template")){event.preventDefault();event.dataTransfer.dropEffect="copy";}}} onDrop={event=>{event.preventDefault();addTemplate(event.dataTransfer.getData("application/relay-template"));}}>
        <div className="workflow-objective"><label>Objective</label><textarea value={objective} onChange={event=>setObjective(event.target.value)} placeholder="What should this workflow accomplish?"/><button className="primary" disabled={running} onClick={()=>void run()}><Play size={15}/>{running?"Starting…":"Run workflow"}</button></div>
        <div className="workflow-chain">{steps.length?steps.map((step,index)=><div className="workflow-node" draggable key={step.id} onDragStart={event=>{event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("application/relay-step",step.id);}} onDragOver={event=>{if(event.dataTransfer.types.includes("application/relay-step"))event.preventDefault();}} onDrop={event=>{event.preventDefault();event.stopPropagation();reorder(event.dataTransfer.getData("application/relay-step"),step.id);}}><div className="workflow-node-head"><GripVertical size={16}/><em>{index+1}</em><input value={step.name} aria-label={`Step ${index+1} name`} onChange={event=>setSteps(current=>current.map(item=>item.id===step.id?{...item,name:event.target.value}:item))}/><button aria-label={`Delete ${step.name}`} onClick={()=>setSteps(current=>current.filter(item=>item.id!==step.id))}><Trash2 size={15}/></button></div><textarea value={step.prompt} aria-label={`${step.name} prompt`} onChange={event=>setSteps(current=>current.map(item=>item.id===step.id?{...item,prompt:event.target.value}:item))}/><SelectMenu ariaLabel={`${step.name} model`} value={step.modelHint??""} onChange={value=>setSteps(current=>current.map(item=>item.id===step.id?{...item,modelHint:value||undefined}:item))} options={modelOptions} icon={Boxes}/>{index<steps.length-1&&<div className="workflow-connector"/>}</div>):<div className="workflow-drop"><Workflow size={24}/><strong>Drop workflow steps here</strong><span>You can also click a step in the library.</span></div>}</div>
        {error&&<div className="form-error workflow-error">{error}</div>}
      </section>
    </div>
    <h3 className="section-heading">Recent runs</h3><div className="list-card">{jobs.length ? jobs.map((job) => <div className="job-row" key={job.id}><Workflow size={18}/><div><strong>{String(job.input.objective)}</strong><span>{job.type} · {String(job.state.stage??job.status)} · updated {new Date(job.updatedAt).toLocaleTimeString()}</span>{job.result?.output && <details><summary>Result</summary><pre>{job.result.output}</pre></details>}{job.error && <small className="form-error">{job.error}</small>}</div><span className={`status ${job.status}`}>{job.status}</span>{["queued", "running", "waiting_approval"].includes(job.status) && <button className="danger" onClick={async () => { await api.cancelJob(job.id); await refresh(); }}>Cancel</button>}</div>) : <Empty icon={Workflow} text="No workflows have run."/>}</div>
  </Page>;
}
function AgentsView({agents}:{agents:api.Agent[]}){return <Page title="Agent registry" subtitle="Reproducible execution graphs pinned to prompts, tools, and routing lanes."><div className="agent-grid">{agents.map(agent=><div className="agent-card" key={agent.id}><div className="agent-head"><div className="provider-icon"><GitBranch size={18}/></div><div><h3>{agent.name}</h3><span>{agent.id} · max {agent.maxSteps} steps</span></div><em>{agent.priority}</em></div><div className="agent-flow"><div>Prompt<strong>{agent.prompt.name}@{agent.prompt.version}</strong></div><i>→</i>{agent.id==="planner-reviewer"?<><div>Planner<strong>plan</strong></div><i>→</i><div>Executor<strong>{agent.tools.length} tools</strong></div><i>→</i><div>Reviewer<strong>repair</strong></div></>:<div>Model loop<strong>{agent.tools.length} tools</strong></div>}</div></div>)}</div></Page>}
function PromptsView({ prompts, refresh }: { prompts: api.Prompt[]; refresh: () => Promise<void> }) { return <Page title="Prompt registry" subtitle="Versioned prompts with an auditable production alias."><div className="model-grid">{prompts.flatMap((prompt) => prompt.versions.map((version) => { const channels=Object.entries(prompt.aliases).filter(([,target])=>target===version).map(([channel])=>channel);return <div className="model-card" key={`${prompt.name}-${version}`}><div className="model-top"><FileCode2/><span className={channels.includes("production") ? "connected" : "pending"}>{channels.join(", ") || "unpromoted"}</span></div><h3>{prompt.name}@{version}</h3><p>packages/prompts/{prompt.name}/{version}.md</p>{!channels.includes("production") && <button className="primary compact" onClick={async () => { await api.promotePrompt(prompt.name, version); await refresh(); }}>Promote</button>}</div>; }))}</div></Page>; }
function EvalsView({reports,refresh}:{reports:api.EvalReport[];refresh:()=>Promise<void>}){const[running,setRunning]=useState(false);return <Page title="Evaluation dashboard" subtitle="Regression results gate prompt and routing changes." action={<button className="primary compact" disabled={running} onClick={async()=>{setRunning(true);try{await api.runEval();await refresh();}finally{setRunning(false);}}}><FlaskConical size={14}/>{running?"Running…":"Run smoke eval"}</button>}><div className="list-card">{reports.length?reports.map(report=><div className="eval-report" key={report.id}><div className={`eval-score ${report.failed?"bad":"good"}`}>{Math.round(report.passRate*100)}%</div><div><strong>{report.passed} passed · {report.failed} failed</strong><span>{new Date(report.createdAt).toLocaleString()} · {report.id.slice(0,8)}</span><div className="eval-cases">{report.results.map(result=><span className={result.passed?"pass":"fail"} key={result.id}>{result.passed?<Check size={11}/>:<X size={11}/>} {result.id} · {Math.round(result.latencyMs)}ms</span>)}</div></div></div>):<Empty icon={FlaskConical} text="No evaluation runs yet."/>}</div></Page>}
function UsageView({ usage, traces,policy }: { usage: api.Usage; traces: api.Trace[];policy:api.Policy|null }) { const limit=policy?.monthlyBudgetUsd??100,percent=limit?usage.costUsd/limit*100:100;const cards = [{ label: "Total requests", value: usage.requests.toString(), icon: Activity }, { label: "Tokens processed", value: (usage.inputTokens + usage.outputTokens).toLocaleString(), icon: Braces }, { label: "Model spend", value: `$${usage.costUsd.toFixed(4)}`, icon: CircleDollarSign }, { label: "Success rate", value: traces.length ? `${Math.round(traces.filter((t) => t.status === "ok").length / traces.length * 100)}%` : "—", icon: Check }]; return <Page title="Usage & economics" subtitle="Token volume, request health, and spend against budget."><div className="stat-grid">{cards.map(({ label, value, icon: Icon }) => <div className="stat-card" key={label}><div><span>{label}</span><strong>{value}</strong></div><Icon size={19}/></div>)}</div><div className={`budget-card ${percent>=80?"budget-warning":""}`}><div><span className="eyebrow">MONTHLY BUDGET</span><h3>${usage.costUsd.toFixed(2)} <small>of ${limit.toFixed(2)}</small></h3></div><div className="budget-track"><i style={{ width: `${Math.min(100, Math.max(.5, percent))}%` }}/></div><p>{percent>=80?`Budget alert: ${percent.toFixed(1)}% consumed.`:"Budget enforcement is active. Requests fail closed at the tenant limit."}</p></div></Page>; }
function ModelsView({ providers }: { providers: api.ProviderStatus[] }) { return <Page title="Models & providers" subtitle="Live credential and endpoint checks for every policy route."><div className="model-grid">{providers.map((item) => <div className="model-card" key={item.id}><div className="model-top"><div className="provider-icon"><Bot size={19}/></div><span className={item.health?.ok ? "connected" : "pending"}>{!item.configured ? "Needs key" : item.health?.ok ? `Healthy · ${item.health.latencyMs}ms` : "Unavailable"}</span></div><h3>{item.model ?? item.provider ?? item.id}</h3><p>{item.provider ?? item.id} · {item.id}</p>{item.health?.error && <small className="provider-error">{item.health.error}</small>}<div className="capabilities"><span><Braces size={12}/> {item.capabilities?.streaming ? "Streaming" : "Not active"}</span><span><Clock3 size={12}/> {item.capabilities?.selfHosted ? "Private" : "Managed"}</span></div></div>)}</div><div className="setup-note"><KeyRound/><div><strong>Credentials stay server-side</strong><span>Put provider keys in the API environment. For private inference, Relay already targets the local OpenAI-compatible endpoint at <code>127.0.0.1:11434/v1</code>.</span></div></div></Page>; }
function PoliciesView({ audit,policy }: { audit: api.AuditEvent[];policy:api.Policy|null }) { return <Page title="Policies & audit" subtitle="Guardrails and immutable operator activity for this tenant."><div className="policy-layout">{[{ icon: Network, title: "Provider allowlist", detail: policy?.allowedProviders.join(", ")??"Loading", tag: `${policy?.allowedProviders.length??0} allowed` }, { icon: CircleDollarSign, title: "Monthly spend limit", detail: "Hard stop when tenant usage reaches budget", tag: `$${(policy?.monthlyBudgetUsd??0).toFixed(2)}` }, { icon: KeyRound, title: "Write tool approval", detail: "A human must approve every side effect", tag: policy?.writeToolsRequireApproval?"Required":"Optional" }].map(({ icon: Icon, title, detail, tag }) => <div className="policy-row" key={title}><Icon size={18}/><div><strong>{title}</strong><span>{detail}</span></div><em>{tag}</em></div>)}</div><h3 className="section-heading">Recent audit events</h3><div className="list-card">{audit.map((event) => <div className="audit-row" key={event.id}><Activity size={15}/><strong>{event.action}</strong><span>{event.resourceType}{event.resourceId ? ` · ${event.resourceId.slice(0, 18)}` : ""}</span><time>{new Date(event.createdAt).toLocaleString()}</time></div>)}</div></Page>; }
