import {z} from "zod";

export const workflowNodeTypeSchema=z.enum(["trigger.manual","input.form","ai.prompt","agent.custom","data.transform","control.condition","human.approval","integration.http","reliability.error-boundary","output.response"]);
export const workflowNodeSchema=z.object({id:z.string().regex(/^[A-Za-z][A-Za-z0-9_-]{0,63}$/),type:workflowNodeTypeSchema,typeVersion:z.string().default("1.0.0"),name:z.string().trim().min(1).max(120),position:z.object({x:z.number().finite(),y:z.number().finite()}).strict(),config:z.record(z.unknown()).default({}),retryPolicy:z.object({maximumAttempts:z.number().int().min(1).max(10),backoff:z.enum(["fixed","exponential"]),initialDelayMs:z.number().int().min(0).max(300_000),maximumDelayMs:z.number().int().min(0).max(3_600_000),jitter:z.boolean()}).strict().optional(),timeoutMs:z.number().int().positive().max(86_400_000).optional(),metadata:z.object({description:z.string().max(1000).optional(),tags:z.array(z.string().max(50)).max(20).optional(),collapsed:z.boolean().optional()}).strict().optional()}).strict();
export const workflowEdgeSchema=z.object({id:z.string().regex(/^[A-Za-z][A-Za-z0-9_-]{0,63}$/),source:z.object({nodeId:z.string(),portId:z.string().default("output")}).strict(),target:z.object({nodeId:z.string(),portId:z.string().default("input")}).strict(),label:z.string().max(80).optional()}).strict();
export const workflowDefinitionSchema=z.object({$schema:z.string().url().optional(),schemaVersion:z.literal("1.0"),id:z.string().min(1).max(80),name:z.string().min(1).max(120),description:z.string().max(2000).default(""),inputs:z.record(z.unknown()).default({type:"object"}),nodes:z.array(workflowNodeSchema).min(2).max(100),edges:z.array(workflowEdgeSchema).max(200),policies:z.object({maximumRunDurationMs:z.number().int().positive().max(86_400_000).default(1_800_000),maximumRunCostUsd:z.number().nonnegative().max(1000).default(5),maximumParallelism:z.number().int().min(1).max(32).default(4),failureMode:z.literal("fail-closed").default("fail-closed")}).strict().default({maximumRunDurationMs:1_800_000,maximumRunCostUsd:5,maximumParallelism:4,failureMode:"fail-closed"})}).strict();
export type WorkflowDefinition=z.infer<typeof workflowDefinitionSchema>;
export type WorkflowNode=z.infer<typeof workflowNodeSchema>;
export type WorkflowEdge=z.infer<typeof workflowEdgeSchema>;
export type WorkflowDiagnostic={code:string;severity:"error"|"warning";message:string;nodeId?:string;edgeId?:string;path?:string};
export type WorkflowRecord={id:string;tenantId:string;name:string;description:string;createdAt:string;updatedAt:string};
export type WorkflowDraft={workflowId:string;revision:number;definition:WorkflowDefinition;contentHash:string;updatedBy?:string;updatedAt:string};
export type WorkflowVersion={id:string;workflowId:string;versionNumber:number;definition:WorkflowDefinition;compiledPlan:{nodeOrder:string[]};contentHash:string;releaseNotes:string;publishedBy?:string;publishedAt:string};
export const createWorkflowSchema=z.object({name:z.string().trim().min(1).max(120),description:z.string().trim().max(2000).optional()}).strict();
export const publishWorkflowSchema=z.object({releaseNotes:z.string().trim().max(4000).default("")}).strict();
export const startWorkflowRunSchema=z.object({input:z.record(z.unknown()).default({})}).strict();

export function validateWorkflowGraph(definition:WorkflowDefinition):WorkflowDiagnostic[]{const diagnostics:WorkflowDiagnostic[]=[],nodes=new Map<string,WorkflowNode>(),edges=new Set<string>();for(const [index,node]of definition.nodes.entries()){if(nodes.has(node.id))diagnostics.push({code:"duplicate_node_id",severity:"error",message:`Node identifier ${node.id} is duplicated.`,nodeId:node.id,path:`/nodes/${index}/id`});nodes.set(node.id,node);}for(const [index,edge]of definition.edges.entries()){if(edges.has(edge.id))diagnostics.push({code:"duplicate_edge_id",severity:"error",message:`Edge identifier ${edge.id} is duplicated.`,edgeId:edge.id,path:`/edges/${index}/id`});edges.add(edge.id);if(!nodes.has(edge.source.nodeId))diagnostics.push({code:"missing_source_node",severity:"error",message:`Source node ${edge.source.nodeId} does not exist.`,edgeId:edge.id,path:`/edges/${index}/source`});if(!nodes.has(edge.target.nodeId))diagnostics.push({code:"missing_target_node",severity:"error",message:`Target node ${edge.target.nodeId} does not exist.`,edgeId:edge.id,path:`/edges/${index}/target`});}
  const triggers=definition.nodes.filter(node=>node.type.startsWith("trigger."));if(triggers.length!==1)diagnostics.push({code:"manual_trigger_required",severity:"error",message:"The initial release requires exactly one trigger node."});const outputs=definition.nodes.filter(node=>node.type.startsWith("output."));if(!outputs.length)diagnostics.push({code:"output_required",severity:"error",message:"At least one output node is required."});
  const adjacency=new Map<string,string[]>();for(const node of definition.nodes)adjacency.set(node.id,[]);for(const edge of definition.edges)if(nodes.has(edge.source.nodeId)&&nodes.has(edge.target.nodeId))adjacency.get(edge.source.nodeId)!.push(edge.target.nodeId);const visiting=new Set<string>(),visited=new Set<string>();const visit=(id:string):void=>{if(visiting.has(id)){diagnostics.push({code:"cycle_not_allowed",severity:"error",message:"Cycles require an explicit bounded-loop node.",nodeId:id});return;}if(visited.has(id))return;visiting.add(id);for(const next of adjacency.get(id)??[])visit(next);visiting.delete(id);visited.add(id);};for(const node of definition.nodes)visit(node.id);if(triggers[0]){const reachable=new Set<string>();const walk=(id:string)=>{if(reachable.has(id))return;reachable.add(id);for(const next of adjacency.get(id)??[])walk(next);};walk(triggers[0].id);for(const node of definition.nodes)if(!reachable.has(node.id))diagnostics.push({code:"unreachable_node",severity:"error",message:`${node.name} is not reachable from the trigger.`,nodeId:node.id});}for(const node of definition.nodes){if(node.type==="ai.prompt"&&typeof node.config.prompt!=="string")diagnostics.push({code:"prompt_required",severity:"error",message:"Prompt nodes require prompt text.",nodeId:node.id,path:"/config/prompt"});if(node.type==="human.approval"&&!definition.edges.some(edge=>edge.source.nodeId===node.id))diagnostics.push({code:"approval_path_required",severity:"error",message:"Approval nodes require a continuation path.",nodeId:node.id});}return diagnostics;}

export function compileWorkflow(definition:WorkflowDefinition):{nodeOrder:string[]}{const incoming=new Map(definition.nodes.map(node=>[node.id,0])),adjacency=new Map(definition.nodes.map(node=>[node.id,[] as string[]]));for(const edge of definition.edges){if(incoming.has(edge.target.nodeId))incoming.set(edge.target.nodeId,incoming.get(edge.target.nodeId)!+1);adjacency.get(edge.source.nodeId)?.push(edge.target.nodeId);}const queue=definition.nodes.filter(node=>incoming.get(node.id)===0).map(node=>node.id),order:string[]=[];while(queue.length){const id=queue.shift()!;order.push(id);for(const next of adjacency.get(id)??[]){incoming.set(next,incoming.get(next)!-1);if(incoming.get(next)===0)queue.push(next);}}return{nodeOrder:order};}
