import { randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "pg";
import type { ApprovalRecord, ArtifactRecord, AuditEvent, ChatMessage, JobRecord, JobStatus, TenantPolicy, Trace, UsageRecord, UsageSummary } from "@relay/contracts";
import { defaultPolicy, MemoryStore, type RelayStore, type Session } from "./store.js";

export class PostgresStore implements RelayStore {
  readonly pool: Pool;
  constructor(connectionString: string) { this.pool = new Pool({ connectionString, max: Number(process.env.DATABASE_POOL_SIZE ?? 10), idleTimeoutMillis: 30_000 }); }

  private async ensureTenant(client: Pool | PoolClient, tenantId: string): Promise<string> {
    const result = await client.query<{ id: string }>(`INSERT INTO tenants (id, slug, name, policy) VALUES ($1::uuid, $2, $3, $4::jsonb) ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug RETURNING id`, [tenantId, `tenant-${tenantId.slice(0, 8)}`, `Tenant ${tenantId.slice(0, 8)}`, JSON.stringify(defaultPolicy(tenantId))]);
    return result.rows[0]!.id;
  }

  async session(tenantId: string, id: string): Promise<Session> {
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN"); await this.ensureTenant(client, tenantId);
      const result = await client.query(`INSERT INTO sessions (id, tenant_id) VALUES ($1::uuid, $2::uuid) ON CONFLICT (id) DO UPDATE SET updated_at = sessions.updated_at RETURNING id, tenant_id, created_at, updated_at`, [id, tenantId]);
      const messages = await client.query<{ role: ChatMessage["role"]; content: unknown; name: string | null; tool_call_id: string | null; tool_calls: ChatMessage["toolCalls"] | null }>(`SELECT role, content, name, tool_call_id, tool_calls FROM messages WHERE session_id = $1::uuid ORDER BY sequence`, [id]);
      await client.query("COMMIT"); const row = result.rows[0]!;
      return { id: row.id, tenantId: row.tenant_id, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString(), messages: messages.rows.map((m) => ({ role: m.role, content: m.content, name: m.name ?? undefined, toolCallId: m.tool_call_id ?? undefined, toolCalls: m.tool_calls ?? undefined })) };
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }

  async listSessions(tenantId: string, limit = 50): Promise<Session[]> {
    const result = await this.pool.query(`SELECT id FROM sessions WHERE tenant_id=$1::uuid ORDER BY updated_at DESC LIMIT $2`, [tenantId, limit]);
    return await Promise.all(result.rows.map((row) => this.session(tenantId, row.id)));
  }

  async saveMessages(tenantId: string, id: string, messages: ChatMessage[]): Promise<Session> {
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN"); await this.ensureTenant(client, tenantId);
      await client.query(`INSERT INTO sessions (id, tenant_id) VALUES ($1::uuid, $2::uuid) ON CONFLICT (id) DO UPDATE SET updated_at = now()`, [id, tenantId]);
      await client.query(`DELETE FROM messages WHERE session_id = $1::uuid`, [id]);
      for (let index = 0; index < messages.length; index += 1) { const m = messages[index]!; await client.query(`INSERT INTO messages (session_id, sequence, role, content, name, tool_call_id, tool_calls) VALUES ($1::uuid,$2,$3,$4::jsonb,$5,$6,$7::jsonb)`, [id, index, m.role, JSON.stringify(m.content), m.name ?? null, m.toolCallId ?? null, JSON.stringify(m.toolCalls ?? null)]); }
      await client.query("COMMIT"); return await this.session(tenantId, id);
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }

  async saveTrace(trace: Trace): Promise<void> { await this.ensureTenant(this.pool, trace.tenantId); await this.pool.query(`INSERT INTO traces (id, tenant_id, session_id, status, data, started_at, ended_at) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5::jsonb,$6,$7) ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status,data=EXCLUDED.data,ended_at=EXCLUDED.ended_at`, [trace.id, trace.tenantId, trace.sessionId, trace.status, JSON.stringify(trace), trace.startedAt, trace.status === "running" ? null : new Date().toISOString()]); }
  async trace(id: string): Promise<Trace | undefined> { const result = await this.pool.query<{ data: Trace }>(`SELECT data FROM traces WHERE id=$1::uuid`, [id]); return result.rows[0]?.data; }
  async listTraces(tenantId: string, limit = 100): Promise<Trace[]> { const result = await this.pool.query<{ data: Trace }>(`SELECT data FROM traces WHERE tenant_id=$1::uuid ORDER BY started_at DESC LIMIT $2`, [tenantId, limit]); return result.rows.map((row) => row.data); }
  async addUsage(record: UsageRecord): Promise<void> { await this.pool.query(`INSERT INTO usage_records (id,tenant_id,session_id,trace_id,provider,model,input_tokens,output_tokens,cost_usd,created_at) VALUES ($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7,$8,$9,$10)`, [record.id, record.tenantId, record.sessionId, record.traceId, record.provider, record.model, record.inputTokens, record.outputTokens, record.costUsd, record.createdAt]); }
  async usageSummary(tenantId: string): Promise<UsageSummary> { const result = await this.pool.query(`SELECT count(*)::int requests, coalesce(sum(input_tokens),0)::int input_tokens, coalesce(sum(output_tokens),0)::int output_tokens, coalesce(sum(cost_usd),0)::float cost_usd FROM usage_records WHERE tenant_id=$1::uuid AND created_at >= date_trunc('month',now())`, [tenantId]); const r = result.rows[0]; return { requests: r.requests, inputTokens: r.input_tokens, outputTokens: r.output_tokens, costUsd: r.cost_usd }; }
  async tenantPolicy(tenantId: string): Promise<TenantPolicy> { await this.ensureTenant(this.pool, tenantId); const result = await this.pool.query<{ policy: TenantPolicy }>(`SELECT policy FROM tenants WHERE id=$1::uuid`, [tenantId]); return { ...defaultPolicy(tenantId), ...result.rows[0]?.policy, tenantId }; }
  async saveTenantPolicy(policy: TenantPolicy): Promise<void> { await this.ensureTenant(this.pool, policy.tenantId); await this.pool.query(`UPDATE tenants SET policy=$2::jsonb WHERE id=$1::uuid`, [policy.tenantId, JSON.stringify(policy)]); }
  async addAudit(event: Omit<AuditEvent, "id" | "createdAt">): Promise<AuditEvent> { const record: AuditEvent = { ...event, id: randomUUID(), createdAt: new Date().toISOString() }; await this.pool.query(`INSERT INTO audit_events (id,tenant_id,actor_id,action,resource_type,resource_id,trace_id,metadata,created_at) VALUES ($1::uuid,$2::uuid,$3::uuid,$4,$5,$6,$7::uuid,$8::jsonb,$9)`, [record.id, record.tenantId, record.actorId ?? null, record.action, record.resourceType, record.resourceId ?? null, record.traceId ?? null, JSON.stringify(record.metadata), record.createdAt]); return record; }
  async listAudit(tenantId: string, limit = 100): Promise<AuditEvent[]> { const result = await this.pool.query(`SELECT id,tenant_id,actor_id,action,resource_type,resource_id,trace_id,metadata,created_at FROM audit_events WHERE tenant_id=$1::uuid ORDER BY created_at DESC LIMIT $2`, [tenantId, limit]); return result.rows.map((r) => ({ id:r.id, tenantId:r.tenant_id, actorId:r.actor_id ?? undefined, action:r.action, resourceType:r.resource_type, resourceId:r.resource_id ?? undefined, traceId:r.trace_id ?? undefined, metadata:r.metadata, createdAt:new Date(r.created_at).toISOString() })); }
  private mapApproval(row:any):ApprovalRecord{return{id:row.id,tenantId:row.tenant_id,sessionId:row.session_id,traceId:row.trace_id,toolCallId:row.tool_call_id??undefined,toolName:row.tool_name,input:row.input,status:row.status,requestedAt:new Date(row.requested_at).toISOString(),resolvedAt:row.resolved_at?new Date(row.resolved_at).toISOString():undefined,resolvedBy:row.resolved_by??undefined,reason:row.reason??undefined};}
  async createApproval(input:Omit<ApprovalRecord,"id"|"status"|"requestedAt">):Promise<ApprovalRecord>{const id=randomUUID();const result=await this.pool.query(`INSERT INTO approvals(id,tenant_id,session_id,trace_id,tool_call_id,tool_name,input,status) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7::jsonb,'pending') RETURNING *`,[id,input.tenantId,input.sessionId,input.traceId,input.toolCallId??null,input.toolName,JSON.stringify(input.input)]);return this.mapApproval(result.rows[0]);}
  async approval(id:string):Promise<ApprovalRecord|undefined>{const result=await this.pool.query(`SELECT * FROM approvals WHERE id=$1::uuid`,[id]);return result.rows[0]?this.mapApproval(result.rows[0]):undefined;}
  async listApprovals(tenantId:string,status?:ApprovalRecord["status"]):Promise<ApprovalRecord[]>{const result=await this.pool.query(`SELECT * FROM approvals WHERE tenant_id=$1::uuid AND ($2::text IS NULL OR status=$2) ORDER BY requested_at DESC`,[tenantId,status??null]);return result.rows.map(row=>this.mapApproval(row));}
  async resolveApproval(id:string,status:"approved"|"rejected",actorId:string,reason?:string):Promise<ApprovalRecord>{const result=await this.pool.query(`UPDATE approvals SET status=$2,resolved_by=$3::uuid,resolved_at=now(),reason=$4 WHERE id=$1::uuid AND status='pending' RETURNING *`,[id,status,actorId,reason??null]);if(!result.rows[0])throw new Error("Approval not found or already resolved");return this.mapApproval(result.rows[0]);}
  private mapJob(r:any):JobRecord{return{id:r.id,tenantId:r.tenant_id,actorId:r.actor_id??undefined,type:r.type,status:r.status,input:r.input,state:r.state,result:r.result??undefined,error:r.error??undefined,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()};}
  async createJob(input:Omit<JobRecord,"id"|"status"|"state"|"createdAt"|"updatedAt">):Promise<JobRecord>{const id=randomUUID();const result=await this.pool.query(`INSERT INTO jobs(id,tenant_id,actor_id,type,status,input,state) VALUES($1::uuid,$2::uuid,$3::uuid,$4,'queued',$5::jsonb,'{}'::jsonb) RETURNING *`,[id,input.tenantId,input.actorId??null,input.type,JSON.stringify(input.input)]);return this.mapJob(result.rows[0]);}
  async job(id:string):Promise<JobRecord|undefined>{const result=await this.pool.query(`SELECT * FROM jobs WHERE id=$1::uuid`,[id]);return result.rows[0]?this.mapJob(result.rows[0]):undefined;}
  async listJobs(tenantId:string,status?:JobStatus):Promise<JobRecord[]>{const result=await this.pool.query(`SELECT * FROM jobs WHERE tenant_id=$1::uuid AND ($2::text IS NULL OR status=$2) ORDER BY created_at DESC`,[tenantId,status??null]);return result.rows.map(row=>this.mapJob(row));}
  async recoverableJobs():Promise<JobRecord[]>{const result=await this.pool.query(`SELECT * FROM jobs WHERE status='queued' OR (status='running' AND lease_expires_at<now()) ORDER BY created_at`);return result.rows.map(row=>this.mapJob(row));}
  async claimJob(id:string,workerId:string,leaseSeconds=300):Promise<JobRecord|undefined>{const result=await this.pool.query(`UPDATE jobs SET status='running',lease_owner=$2,lease_expires_at=now()+($3*interval '1 second'),updated_at=now() WHERE id=$1::uuid AND (status='queued' OR (status='running' AND lease_expires_at<now())) RETURNING *`,[id,workerId,leaseSeconds]);return result.rows[0]?this.mapJob(result.rows[0]):undefined;}
  async updateJob(id:string,patch:Partial<Pick<JobRecord,"status"|"state"|"result"|"error">>):Promise<JobRecord>{const current=await this.job(id);if(!current)throw new Error("Job not found");const status=patch.status??current.status,terminal=["succeeded","failed","cancelled","waiting_approval"].includes(status);const result=await this.pool.query(`UPDATE jobs SET status=$2,state=$3::jsonb,result=$4::jsonb,error=$5,updated_at=now(),lease_owner=CASE WHEN $6 THEN NULL ELSE lease_owner END,lease_expires_at=CASE WHEN $6 THEN NULL ELSE lease_expires_at END WHERE id=$1::uuid RETURNING *`,[id,status,JSON.stringify(patch.state??current.state),JSON.stringify(patch.result??current.result??null),patch.error??current.error??null,terminal]);return this.mapJob(result.rows[0]);}
  private mapArtifact(r:any):ArtifactRecord{return{id:r.id,tenantId:r.tenant_id,jobId:r.job_id??undefined,sessionId:r.session_id??undefined,name:r.name,mediaType:r.media_type,content:r.content,sizeBytes:r.size_bytes,createdAt:new Date(r.created_at).toISOString()};}
  async createArtifact(input:Omit<ArtifactRecord,"id"|"createdAt"|"sizeBytes">):Promise<ArtifactRecord>{const id=randomUUID(),encoded=JSON.stringify(input.content);const result=await this.pool.query(`INSERT INTO artifacts(id,tenant_id,job_id,session_id,name,media_type,content,size_bytes) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7::jsonb,$8) RETURNING *`,[id,input.tenantId,input.jobId??null,input.sessionId??null,input.name,input.mediaType,encoded,Buffer.byteLength(encoded)]);return this.mapArtifact(result.rows[0]);}
  async listArtifacts(tenantId:string,jobId?:string):Promise<ArtifactRecord[]>{const result=await this.pool.query(`SELECT * FROM artifacts WHERE tenant_id=$1::uuid AND ($2::uuid IS NULL OR job_id=$2::uuid) ORDER BY created_at DESC`,[tenantId,jobId??null]);return result.rows.map(row=>this.mapArtifact(row));}
  async purgeBefore(tenantId:string,before:Date):Promise<Record<string,number>>{const client=await this.pool.connect();try{await client.query("BEGIN");const artifacts=await client.query(`DELETE FROM artifacts WHERE tenant_id=$1::uuid AND created_at<$2`,[tenantId,before]);const approvals=await client.query(`DELETE FROM approvals WHERE tenant_id=$1::uuid AND requested_at<$2 AND status<>'pending'`,[tenantId,before]);const usage=await client.query(`DELETE FROM usage_records WHERE tenant_id=$1::uuid AND created_at<$2`,[tenantId,before]);const audit=await client.query(`DELETE FROM audit_events WHERE tenant_id=$1::uuid AND created_at<$2`,[tenantId,before]);const traces=await client.query(`DELETE FROM traces WHERE tenant_id=$1::uuid AND started_at<$2 AND NOT EXISTS(SELECT 1 FROM approvals a WHERE a.trace_id=traces.id)`,[tenantId,before]);const messages=await client.query(`DELETE FROM messages USING sessions WHERE messages.session_id=sessions.id AND sessions.tenant_id=$1::uuid AND sessions.updated_at<$2`,[tenantId,before]);await client.query("COMMIT");return{artifacts:artifacts.rowCount??0,approvals:approvals.rowCount??0,usage:usage.rowCount??0,audit:audit.rowCount??0,traces:traces.rowCount??0,messages:messages.rowCount??0};}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
  async close(): Promise<void> { await this.pool.end(); }
}

export function storeFromEnvironment(env: NodeJS.ProcessEnv = process.env): RelayStore { return env.DATABASE_URL ? new PostgresStore(env.DATABASE_URL) : new MemoryStore(); }
