import Fastify, { type FastifyReply, type FastifyRequest } from "fastify";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import cors from "@fastify/cors";
import rateLimit from "@fastify/rate-limit";
import staticFiles from "@fastify/static";
import { adaptersFromEnvironment } from "@relay/adapters";
import { agentDefinitionSchema,approvalDecisionSchema,artifactUploadSchema,bootstrapSchema,chatRequestSchema,createJobSchema,createWorkflowSchema,loginSchema,publishWorkflowSchema,promptPromotionSchema,retentionPurgeSchema,startWorkflowRunSchema,tenantPolicySchema,type AgentDefinition,type AuthPrincipal,type TenantRole } from "@relay/contracts";
import { Orchestrator, PromptRegistry, storeFromEnvironment } from "@relay/orchestrator";
import { createDefaultToolRunner } from "@relay/tool-runner";
import { runEvalDataset, WorkflowEngine } from "@relay/workers";
import { AuthService } from "./auth.js";
import { assertSafeProductionConfiguration,parseAllowedOrigins } from "./config.js";
import {WorkflowCatalog} from "./workflow-catalog.js";

export function createApp(env: NodeJS.ProcessEnv = process.env) {
  assertSafeProductionConfiguration(env);
  const app = Fastify({ logger: { level: env.LOG_LEVEL ?? "info" } });
  const auth = new AuthService(env);
  const store = storeFromEnvironment(env);
  const adapters = adaptersFromEnvironment(env);
  const promptRoot=env.PROMPTS_DIR??fileURLToPath(new URL("../../../packages/prompts/",import.meta.url));
  const agentsFile=env.AGENTS_FILE??fileURLToPath(new URL("../../../config/agents.json",import.meta.url));
  const evalDataset=env.EVAL_DATASET??fileURLToPath(new URL("../../../evals/datasets/smoke.jsonl",import.meta.url));
  const webRoot=env.WEB_DIST_DIR??fileURLToPath(new URL("../../../apps/web/dist",import.meta.url));
  const prompts=new PromptRegistry(promptRoot);
  const orchestrator = new Orchestrator(adapters, createDefaultToolRunner(), store,undefined,prompts);
  const workflows=new WorkflowEngine(orchestrator,store);
  const workflowCatalog=new WorkflowCatalog(env.DATABASE_URL);
  const loadAgents=async()=>agentDefinitionSchema.array().parse(JSON.parse(await readFile(agentsFile,"utf8"))) as AgentDefinition[];
  const selectedAgent=async(agentId?:string)=>{if(!agentId)return undefined;const agent=(await loadAgents()).find(item=>item.id===agentId);if(!agent)throw new Error(`Agent ${agentId} was not found`);return agent;};
  const allowedOrigins=new Set(parseAllowedOrigins(env));
  app.register(cors,{credentials:true,origin:(origin,callback)=>{if(!origin||env.NODE_ENV!=="production"&&allowedOrigins.size===0||allowedOrigins.has(origin))callback(null,true);else callback(new Error("Origin is not allowed"),false);}});
  if(env.SERVE_WEB==="true") app.register(staticFiles,{root:webRoot,wildcard:false});
  app.register(rateLimit,{global:false,max:Number(env.RATE_LIMIT_MAX??120),timeWindow:env.RATE_LIMIT_WINDOW??"1 minute",keyGenerator:(request)=>auth.verify(request.headers.authorization)?.tenantId??request.ip});
  let checkRateLimit: ReturnType<typeof app.createRateLimit> | undefined;
  app.addHook("onRequest",async(request,reply)=>{
    if (["GET", "HEAD", "OPTIONS"].includes(request.method)) return;
    checkRateLimit??=app.createRateLimit();
    const limit=await checkRateLimit(request);
    if(!limit.isAllowed&&limit.isExceeded){
      const retryAfterSeconds=Math.max(1,Math.ceil(limit.ttlInSeconds));
      reply.header("retry-after",retryAfterSeconds).code(429).send({error:`Too many write requests. Try again in ${retryAfterSeconds} seconds.`,code:"rate_limit_exceeded",retryAfterSeconds});
    }
  });
  app.addHook("onClose", async () => { await Promise.all([store.close(), auth.close(),workflowCatalog.close()]); });
  app.addHook("onReady", async () => { await auth.ready(); await workflows.recoverAll(); });

  const cookieName="relay_session";
  const cookieToken=(request:FastifyRequest)=>request.headers.cookie?.split(";").map(value=>value.trim()).find(value=>value.startsWith(`${cookieName}=`))?.slice(cookieName.length+1);
  const setSessionCookie=(reply:FastifyReply,token:string)=>reply.header("set-cookie",`${cookieName}=${token}; HttpOnly; Path=/; SameSite=Strict; Max-Age=28800${env.NODE_ENV==="production"?"; Secure":""}`);
  function principal(request: FastifyRequest): AuthPrincipal | undefined { return auth.verify(request.headers.authorization)??auth.verify(cookieToken(request))??(auth.mode === "optional" ? auth.developmentPrincipal() : undefined); }
  function guard(request: FastifyRequest, reply: FastifyReply, roles?: TenantRole[]): AuthPrincipal | undefined {
    const actor = principal(request); if (!actor) { reply.code(401).send({ error: "Authentication required" }); return undefined; }
    if (roles && !auth.authorize(actor, roles)) { reply.code(403).send({ error: "Insufficient role" }); return undefined; }
    return actor;
  }

  app.get("/health", async () => ({ status: "ok", service: "relay-api", timestamp: new Date().toISOString() }));
  app.get("/ready", async () => ({ status: "ready", persistence: env.DATABASE_URL ? "postgres" : "memory", auth: auth.mode, adapters: adapters.map((adapter) => ({ id: adapter.id, provider: adapter.provider, model: adapter.model, active: adapter.supports({} as never) })) }));

  app.post("/v1/auth/bootstrap", async (request, reply) => {const parsed=bootstrapSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_bootstrap",error:"Bootstrap validation failed",details:parsed.error.flatten()});try{const result=await auth.bootstrap(parsed.data);setSessionCookie(reply,result.token);return{principal:result.principal};}catch(error){return reply.code(409).send({code:"bootstrap_conflict",error:error instanceof Error?error.message:"Bootstrap failed"});}});
  app.post("/v1/auth/login", async (request, reply) => {const parsed=loginSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_login",error:"Login validation failed",details:parsed.error.flatten()});const result=await auth.login(parsed.data.email,parsed.data.password);if(!result)return reply.code(401).send({code:"invalid_credentials",error:"Invalid credentials"});setSessionCookie(reply,result.token);return{principal:result.principal};});
  app.post("/v1/auth/logout",async(_request,reply)=>{reply.header("set-cookie",`${cookieName}=; HttpOnly; Path=/; SameSite=Strict; Max-Age=0${env.NODE_ENV==="production"?"; Secure":""}`);return{ok:true};});
  app.get("/v1/auth/me", async (request, reply) => { const actor=guard(request,reply); return actor; });

  app.post("/v1/chat", async (request, reply) => {
    const actor=guard(request,reply,["owner","admin","builder"]); if(!actor) return;
    const parsed = chatRequestSchema.safeParse(request.body);
    if (!parsed.success) return reply.code(400).send({ error: "Invalid chat request", details: parsed.error.flatten() });
    try { const agent=await selectedAgent(parsed.data.agentId);return await orchestrator.run({ ...parsed.data, tenantId: actor.tenantId, metadata: { ...parsed.data.metadata, actorId: actor.userId } },{agent}); }
    catch (error) { const message=error instanceof Error ? error.message : "Chat request failed";return reply.code(/Agent .+ was not found/.test(message)?400:503).send({ error: message }); }
  });

  app.post("/v1/chat/stream", async (request, reply) => {
    const actor=guard(request,reply,["owner","admin","builder"]); if(!actor) return;
    const parsed = chatRequestSchema.safeParse(request.body);
    if (!parsed.success) return reply.code(400).send({ error: "Invalid chat request", details: parsed.error.flatten() });
    let agent:AgentDefinition|undefined;
    try{agent=await selectedAgent(parsed.data.agentId);}catch(error){return reply.code(400).send({error:error instanceof Error?error.message:"Agent was not found"});}
    reply.hijack();
    reply.raw.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache, no-transform", connection: "keep-alive", "x-accel-buffering": "no" });
    let eventSequence=0,closed=false;request.raw.on("close",()=>{closed=true;});
    const send = (event: string, data: unknown) => !closed&&reply.raw.write(`id: ${++eventSequence}\nevent: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
    const heartbeat=setInterval(()=>{if(!closed)reply.raw.write(`: heartbeat ${Date.now()}\n\n`);},15_000);
    try {
      send("start", { sessionId: parsed.data.sessionId });
      const { result, trace } = await orchestrator.run({ ...parsed.data, tenantId: actor.tenantId, metadata: { ...parsed.data.metadata, actorId: actor.userId } }, { onDelta: (text) => send("delta", { text }),agent });
      send("route", { provider: result.provider, model: result.model, reason: result.routeReason, traceId: result.traceId });
      send("complete", { result, trace });
    } catch (error) { send("error", { error: error instanceof Error ? error.message : "Chat request failed" }); }
    finally { clearInterval(heartbeat);if(!closed)reply.raw.end(); }
  });

  app.get<{ Params: { tenantId: string; sessionId: string } }>("/v1/tenants/:tenantId/sessions/:sessionId", async (request,reply) => { const actor=guard(request,reply); if(!actor)return; if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({error:"Cross-tenant access denied"}); return await orchestrator.store.getSession(actor.tenantId,request.params.sessionId)??reply.code(404).send({error:"Session not found"}); });
  app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/sessions", async (request,reply) => { const actor=guard(request,reply); if(!actor)return; if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({error:"Cross-tenant access denied"}); return await orchestrator.store.listSessions(actor.tenantId); });
  app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/traces", async (request,reply) => { const actor=guard(request,reply); if(!actor)return; if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({error:"Cross-tenant access denied"}); return await orchestrator.store.listTraces(actor.tenantId); });
  app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/usage", async (request,reply) => { const actor=guard(request,reply); if(!actor)return; if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({error:"Cross-tenant access denied"}); return await orchestrator.store.usageSummary(actor.tenantId); });
  app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/audit", async (request,reply) => { const actor=guard(request,reply,["owner","admin"]); if(!actor)return; if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({error:"Cross-tenant access denied"}); return await orchestrator.store.listAudit(actor.tenantId); });
  app.get<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/policy", async (request,reply) => { const actor=guard(request,reply); if(!actor)return; if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({error:"Cross-tenant access denied"}); return await orchestrator.store.tenantPolicy(actor.tenantId); });
  app.put<{ Params: { tenantId: string } }>("/v1/tenants/:tenantId/policy", async (request,reply) => {const actor=guard(request,reply,["owner","admin"]);if(!actor)return;if(request.params.tenantId!==actor.tenantId)return reply.code(403).send({code:"cross_tenant_denied",error:"Cross-tenant access denied"});const parsed=tenantPolicySchema.omit({tenantId:true}).safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_tenant_policy",error:"Tenant policy validation failed",details:parsed.error.flatten()});const policy={...parsed.data,tenantId:actor.tenantId};await orchestrator.store.saveTenantPolicy(policy);await orchestrator.store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"policy.updated",resourceType:"tenant",resourceId:actor.tenantId,metadata:{}});return policy;});
  app.get("/v1/tools", async (request,reply) => { const actor=guard(request,reply); return actor ? orchestrator.tools.specs() : undefined; });
  app.get("/v1/providers/status", async (request,reply) => {
    const actor=guard(request,reply,["owner","admin"]); if(!actor)return;
    const known=[{id:"openai",configured:Boolean(env.OPENAI_API_KEY)},{id:"anthropic",configured:Boolean(env.ANTHROPIC_API_KEY)},{id:"mistral",configured:Boolean(env.MISTRAL_API_KEY)},{id:"qwen",configured:Boolean(env.QWEN_API_KEY)},{id:"gemini",configured:Boolean(env.GEMINI_API_KEY)},{id:"gemma",configured:Boolean(env.GEMMA_API_KEY&&env.GEMMA_BASE_URL)}];
    const active=await Promise.all(adapters.map(async adapter=>({id:adapter.id,provider:adapter.provider,model:adapter.model,configured:true,capabilities:adapter.capabilities,health:adapter.health?await adapter.health():{ok:true,latencyMs:0}})));
    return {providers:[...known.filter(item=>!active.some(adapter=>adapter.provider===item.id)),...active]};
  });
  app.get("/v1/approvals",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const status=(request.query as {status?:"pending"|"approved"|"rejected"}).status;return await store.listApprovals(actor.tenantId,status);});
  app.post<{Params:{id:string}}>("/v1/approvals/:id/resolve",async(request,reply)=>{const actor=guard(request,reply,["owner","admin"]);if(!actor)return;const parsed=approvalDecisionSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_approval_decision",error:"Approval decision validation failed",details:parsed.error.flatten()});try{const result=await orchestrator.resolveApproval(request.params.id,actor.tenantId,actor.userId,parsed.data.status,parsed.data.reason);await workflows.resumeForApproval(actor.tenantId,request.params.id);return result;}catch(error){return reply.code(409).send({code:"approval_conflict",error:error instanceof Error?error.message:"Approval resolution failed"});}});
  app.post("/v1/jobs",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;const parsed=createJobSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_job",error:"Job validation failed",details:parsed.error.flatten()});try{return reply.code(202).send(await workflows.submit(actor.tenantId,actor.userId,parsed.data.type,{objective:parsed.data.objective,priority:parsed.data.priority,steps:parsed.data.steps}));}catch(error){return reply.code(400).send({code:"job_submission_failed",error:error instanceof Error?error.message:"Job submission failed"});}});
  app.get("/v1/jobs",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return await store.listJobs(actor.tenantId,(request.query as {status?:import("@relay/contracts").JobStatus}).status);});
  app.get<{Params:{id:string}}>("/v1/jobs/:id",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return await store.job(actor.tenantId,request.params.id)??reply.code(404).send({error:"Job not found"});});
  app.post<{Params:{id:string}}>("/v1/jobs/:id/cancel",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;try{return await workflows.cancel(request.params.id,actor.tenantId);}catch(error){return reply.code(404).send({error:error instanceof Error?error.message:"Job not found"});}});
  app.get("/v1/artifacts",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return await store.listArtifacts(actor.tenantId,(request.query as {jobId?:string}).jobId);});
  app.post("/v1/artifacts",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;const parsed=artifactUploadSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_artifact",error:"Artifact validation failed",details:parsed.error.flatten()});const body=parsed.data;if(Buffer.byteLength(JSON.stringify(body.content))>750_000)return reply.code(413).send({code:"artifact_too_large",error:"Artifact exceeds the 750 KB inline limit"});if(!await store.getSession(actor.tenantId,body.sessionId))return reply.code(404).send({code:"session_not_found",error:"Session not found"});const artifact=await store.createArtifact({tenantId:actor.tenantId,sessionId:body.sessionId,name:body.name,mediaType:body.mediaType,content:body.content});await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"artifact.created",resourceType:"artifact",resourceId:artifact.id,metadata:{name:artifact.name,mediaType:artifact.mediaType,untrusted:true}});return reply.code(201).send(artifact);});
  app.get("/v1/agents",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;try{return await loadAgents();}catch(error){return reply.code(500).send({error:error instanceof Error?error.message:"Agent registry unavailable"});}});
  app.post<{Params:{id:string}}>("/v1/traces/:id/replay",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;const trace=await store.trace(actor.tenantId,request.params.id);if(!trace)return reply.code(404).send({error:"Trace not found"});const session=await store.getSession(actor.tenantId,trace.sessionId),lastUser=session?[...session.messages].reverse().find(message=>message.role==="user"):undefined;if(!lastUser)return reply.code(409).send({error:"Trace session has no user turn to replay"});const replaySessionId=randomUUID();const result=await orchestrator.run({tenantId:actor.tenantId,sessionId:replaySessionId,priority:"balanced",messages:[lastUser],metadata:{actorId:actor.userId,replayOf:trace.id}});await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"trace.rerun",resourceType:"trace",resourceId:trace.id,traceId:result.trace.id,metadata:{rerunSessionId:replaySessionId,nondeterministic:true}});return result;});
  app.get("/v1/evals",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const artifacts=await store.listArtifacts(actor.tenantId);return artifacts.filter(item=>item.mediaType==="application/vnd.relay.eval+json").map(item=>item.content);});
  app.post("/v1/evals/run",async(request,reply)=>{const actor=guard(request,reply,["owner","admin"]);if(!actor)return;const evalOrchestrator=new Orchestrator(adaptersFromEnvironment({...env,OPENAI_API_KEY:"",ANTHROPIC_API_KEY:"",MISTRAL_API_KEY:"",QWEN_API_KEY:"",LOCAL_BASE_URL:"disabled"}),createDefaultToolRunner());const report=await runEvalDataset(evalOrchestrator,resolve(evalDataset));await store.createArtifact({tenantId:actor.tenantId,name:`eval-${report.id}.json`,mediaType:"application/vnd.relay.eval+json",content:report});await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"eval.completed",resourceType:"eval",resourceId:report.id,metadata:{passRate:report.passRate,passed:report.passed,failed:report.failed}});return report;});
  app.get("/v1/prompts",async(request,reply)=>{const actor=guard(request,reply);return actor?await prompts.list():undefined;});
  app.get("/v1/prompts/:name/:version",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const {name,version}=request.params as {name:string;version:string};try{const prompt=await prompts.resolve(name,version);return{name:prompt.name,version:prompt.version,content:prompt.content};}catch(error){return reply.code(404).send({error:error instanceof Error?error.message:"Prompt not found"});}});
  app.post("/v1/prompts/promote",async(request,reply)=>{const actor=guard(request,reply,["owner","admin"]);if(!actor)return;const parsed=promptPromotionSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_prompt_promotion",error:"Prompt promotion validation failed",details:parsed.error.flatten()});const body=parsed.data;try{await prompts.promote(body.name,body.version,body.channel);await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"prompt.promoted",resourceType:"prompt",resourceId:`${body.name}@${body.version}`,metadata:{channel:body.channel}});return{ok:true};}catch(error){return reply.code(404).send({code:"prompt_not_found",error:error instanceof Error?error.message:"Prompt not found"});}});
  app.post("/v1/retention/purge",async(request,reply)=>{const actor=guard(request,reply,["owner"]);if(!actor)return;const parsed=retentionPurgeSchema.safeParse(request.body);if(!parsed.success)return reply.code(422).send({code:"invalid_retention_request",error:"Retention validation failed",details:parsed.error.flatten()});const before=new Date(Date.now()-parsed.data.olderThanDays*86400000);const deleted=await store.purgeBefore(actor.tenantId,before);await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"retention.purged",resourceType:"tenant",resourceId:actor.tenantId,metadata:{before:before.toISOString(),deleted}});return{before:before.toISOString(),deleted};});
  app.post("/v1/workflows",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;const parsed=createWorkflowSchema.safeParse(request.body),idempotencyKey=request.headers["idempotency-key"];if(!parsed.success)return reply.code(422).send({code:"invalid_workflow",error:"Workflow validation failed",details:parsed.error.flatten()});if(typeof idempotencyKey!=="string"||idempotencyKey.length<8)return reply.code(400).send({code:"idempotency_key_required",error:"Idempotency-Key header is required"});const result=await workflowCatalog.create(actor.tenantId,actor.userId,{...parsed.data,idempotencyKey});await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"workflow.created",resourceType:"workflow",resourceId:result.workflow.id,metadata:{name:result.workflow.name}});return reply.code(201).header("etag",`\"rev-${result.draft.revision}\"`).send(result);});
  app.get("/v1/workflows",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return{items:await workflowCatalog.list(actor.tenantId),nextCursor:null};});
  app.get<{Params:{id:string}}>("/v1/workflows/:id",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const workflow=await workflowCatalog.workflow(actor.tenantId,request.params.id),draft=workflow?await workflowCatalog.draft(actor.tenantId,workflow.id):undefined;if(!workflow||!draft)return reply.code(404).send({code:"workflow_not_found",error:"Workflow not found"});return reply.header("etag",`\"rev-${draft.revision}\"`).send({...workflow,draftRevision:draft.revision});});
  app.get<{Params:{id:string}}>("/v1/workflows/:id/draft",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const draft=await workflowCatalog.draft(actor.tenantId,request.params.id);return draft?reply.header("etag",`\"rev-${draft.revision}\"`).send(draft):reply.code(404).send({code:"workflow_not_found",error:"Workflow not found"});});
  app.put<{Params:{id:string}}>("/v1/workflows/:id/draft",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;const match=String(request.headers["if-match"]??"").match(/rev-(\d+)/);if(!match)return reply.code(428).send({code:"if_match_required",error:"If-Match draft revision is required"});try{const draft=await workflowCatalog.updateDraft(actor.tenantId,request.params.id,actor.userId,Number(match[1]),request.body);await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"workflow.draft.updated",resourceType:"workflow",resourceId:request.params.id,metadata:{revision:draft.revision,contentHash:draft.contentHash}});return reply.header("etag",`\"rev-${draft.revision}\"`).send(draft);}catch(error){const typed=error as Error&{code?:string;diagnostics?:unknown};if(typed.code==="draft_revision_conflict")return reply.code(412).send({code:typed.code,error:typed.message});return reply.code(422).send({code:"workflow_validation_failed",error:typed.message,diagnostics:typed.diagnostics??[]});}});
  app.post<{Params:{id:string}}>("/v1/workflows/:id/validate",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const draft=request.body&&Object.keys(request.body as object).length?request.body:(await workflowCatalog.draft(actor.tenantId,request.params.id))?.definition;if(!draft)return reply.code(404).send({code:"workflow_not_found",error:"Workflow not found"});const result=workflowCatalog.validate(draft);return{valid:!result.diagnostics.some(item=>item.severity==="error"),diagnostics:result.diagnostics};});
  app.post<{Params:{id:string}}>("/v1/workflows/:id/publish",async(request,reply)=>{const actor=guard(request,reply,["owner","admin"]);if(!actor)return;const parsed=publishWorkflowSchema.safeParse(request.body),key=request.headers["idempotency-key"];if(!parsed.success)return reply.code(422).send({code:"invalid_publication",error:"Publication validation failed",details:parsed.error.flatten()});if(typeof key!=="string"||key.length<8)return reply.code(400).send({code:"idempotency_key_required",error:"Idempotency-Key header is required"});try{const version=await workflowCatalog.publish(actor.tenantId,request.params.id,actor.userId,parsed.data.releaseNotes,key);await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"workflow.version.published",resourceType:"workflowVersion",resourceId:version.id,metadata:{workflowId:version.workflowId,versionNumber:version.versionNumber,contentHash:version.contentHash}});return reply.code(201).send(version);}catch(error){const typed=error as Error&{diagnostics?:unknown};return reply.code(422).send({code:"workflow_publication_failed",error:typed.message,diagnostics:typed.diagnostics??[]});}});
  app.get<{Params:{id:string}}>("/v1/workflows/:id/versions",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return{items:await workflowCatalog.listVersions(actor.tenantId,request.params.id),nextCursor:null};});
  app.get<{Params:{id:string}}>("/v1/workflow-versions/:id",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return await workflowCatalog.version(actor.tenantId,request.params.id)??reply.code(404).send({code:"workflow_version_not_found",error:"Workflow version not found"});});
  app.post<{Params:{id:string}}>("/v1/workflow-versions/:id/runs",async(request,reply)=>{const actor=guard(request,reply,["owner","admin","builder"]);if(!actor)return;const parsed=startWorkflowRunSchema.safeParse(request.body),key=request.headers["idempotency-key"];if(!parsed.success)return reply.code(422).send({code:"invalid_run_input",error:"Run input validation failed",details:parsed.error.flatten()});if(typeof key!=="string"||key.length<8)return reply.code(400).send({code:"idempotency_key_required",error:"Idempotency-Key header is required"});const version=await workflowCatalog.version(actor.tenantId,request.params.id);if(!version)return reply.code(404).send({code:"workflow_version_not_found",error:"Workflow version not found"});const reservation=await workflowCatalog.reserveRun(actor.tenantId,version.id,key);if(!reservation.created){const prior=await store.job(actor.tenantId,reservation.jobId);return prior?reply.code(200).send(prior):reply.code(202).send({id:reservation.jobId,status:"queued",initializing:true});}const job=await workflows.submit(actor.tenantId,actor.userId,"graph",{objective:`Run ${version.definition.name}`,priority:"deep",definition:version.definition,nodeOrder:version.compiledPlan.nodeOrder,runInput:parsed.data.input,workflowVersionId:version.id},reservation.jobId);await store.addAudit({tenantId:actor.tenantId,actorId:actor.userId,action:"workflow.run.started",resourceType:"job",resourceId:job.id,metadata:{jobId:job.id,workflowVersionId:version.id,idempotencyKey:key}});return reply.code(202).send(job);});
  app.get<{Params:{id:string}}>("/v1/jobs/:id/events",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;const job=await store.job(actor.tenantId,request.params.id);if(!job)return reply.code(404).send({code:"job_not_found",error:"Job not found"});const audit=await store.listAudit(actor.tenantId),events=audit.filter(event=>event.resourceId===job.id||event.metadata?.jobId===job.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)).map(event=>({specversion:"1.0",id:event.id,source:`/relay/tenants/${actor.tenantId}`,type:`com.relay.${event.action}`,subject:`jobs/${job.id}`,time:event.createdAt,datacontenttype:"application/json",data:{...event.metadata,actorId:event.actorId,traceId:event.traceId}}));return{items:events,nextCursor:null};});
  app.get("/v1/node-types",async(request,reply)=>{const actor=guard(request,reply);if(!actor)return;return[{type:"trigger.manual",group:"Triggers",label:"Manual trigger",outputs:["output"]},{type:"ai.prompt",group:"AI",label:"Prompt / model",inputs:["input"],outputs:["output"]},{type:"human.approval",group:"Human",label:"Approval",inputs:["subject"],outputs:["approved","rejected"]},{type:"control.condition",group:"Control",label:"Condition",inputs:["input"],outputs:["true","false"]},{type:"data.transform",group:"Data",label:"Transform",inputs:["input"],outputs:["output"]},{type:"integration.http",group:"Integrations",label:"HTTP request",inputs:["input"],outputs:["output","error"]},{type:"reliability.error-boundary",group:"Reliability",label:"Error boundary",inputs:["input"],outputs:["success","error"]},{type:"output.response",group:"Outputs",label:"Response",inputs:["input"]}];});
  if(env.SERVE_WEB==="true") app.get("/*",async(_request,reply)=>reply.sendFile("index.html"));
  return app;
}
