import {createHash,randomUUID} from "node:crypto";
import {Pool} from "pg";
import {compileWorkflow,validateWorkflowGraph,workflowDefinitionSchema,type WorkflowDefinition,type WorkflowDiagnostic,type WorkflowDraft,type WorkflowRecord,type WorkflowVersion} from "@relay/contracts";

const stable=(value:unknown):string=>{if(Array.isArray(value))return`[${value.map(stable).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(",")}}`;return JSON.stringify(value);};
const hash=(value:unknown)=>createHash("sha256").update(stable(value)).digest("hex");
const now=()=>new Date().toISOString();

export function starterWorkflow(id:string,name:string):WorkflowDefinition{return{schemaVersion:"1.0",id,name,description:"Prompt a model, pause for human approval, then return the approved result.",inputs:{type:"object",additionalProperties:false,properties:{request:{type:"string"}}},nodes:[{id:"manual",type:"trigger.manual",typeVersion:"1.0.0",name:"Manual trigger",position:{x:40,y:160},config:{}},{id:"draft",type:"ai.prompt",typeVersion:"1.0.0",name:"Draft response",position:{x:310,y:160},config:{prompt:"Produce a concise, accurate response for the workflow input.",priority:"balanced"}},{id:"approval",type:"human.approval",typeVersion:"1.0.0",name:"Human approval",position:{x:590,y:160},config:{instructions:"Review the draft before it is released."}},{id:"output",type:"output.response",typeVersion:"1.0.0",name:"Return result",position:{x:870,y:160},config:{format:"markdown"}}],edges:[{id:"e_manual_draft",source:{nodeId:"manual",portId:"output"},target:{nodeId:"draft",portId:"input"}},{id:"e_draft_approval",source:{nodeId:"draft",portId:"output"},target:{nodeId:"approval",portId:"subject"}},{id:"e_approval_output",source:{nodeId:"approval",portId:"approved"},target:{nodeId:"output",portId:"input"}}],policies:{maximumRunDurationMs:1_800_000,maximumRunCostUsd:5,maximumParallelism:4,failureMode:"fail-closed"}};}

export class WorkflowCatalog{
  private readonly pool?:Pool;private readonly workflows=new Map<string,WorkflowRecord>();private readonly drafts=new Map<string,WorkflowDraft>();private readonly versions=new Map<string,WorkflowVersion[]>();private readonly idempotency=new Map<string,WorkflowVersion>();private readonly createIdempotency=new Map<string,string>();private readonly runIdempotency=new Map<string,string>();
  constructor(connectionString?:string){if(connectionString)this.pool=new Pool({connectionString,max:4});}
  async create(tenantId:string,actorId:string,input:{name:string;description?:string;idempotencyKey:string}):Promise<{workflow:WorkflowRecord;draft:WorkflowDraft}>{const key=`${tenantId}:${input.idempotencyKey}`,priorId=this.createIdempotency.get(key);if(priorId){const workflow=await this.workflow(tenantId,priorId),draft=await this.draft(tenantId,priorId);if(workflow&&draft)return{workflow,draft};}if(this.pool){const prior=await this.pool.query(`SELECT id FROM workflows WHERE tenant_id=$1::uuid AND idempotency_key=$2`,[tenantId,input.idempotencyKey]);if(prior.rows[0])return{workflow:(await this.workflow(tenantId,prior.rows[0].id))!,draft:(await this.draft(tenantId,prior.rows[0].id))!};}const id=randomUUID(),timestamp=now(),workflow={id,tenantId,name:input.name,description:input.description??"",createdAt:timestamp,updatedAt:timestamp},definition=starterWorkflow(id,input.name),draft={workflowId:id,revision:1,definition,contentHash:hash(definition),updatedBy:actorId,updatedAt:timestamp};if(this.pool){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query(`INSERT INTO workflows(id,tenant_id,name,description,created_by,idempotency_key) VALUES($1::uuid,$2::uuid,$3,$4,$5::uuid,$6)`,[id,tenantId,workflow.name,workflow.description,actorId,input.idempotencyKey]);await client.query(`INSERT INTO workflow_drafts(workflow_id,tenant_id,revision,definition,content_hash,updated_by) VALUES($1::uuid,$2::uuid,1,$3::jsonb,$4,$5::uuid)`,[id,tenantId,JSON.stringify(definition),draft.contentHash,actorId]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}else{this.workflows.set(id,workflow);this.drafts.set(id,draft);this.createIdempotency.set(key,id);}return{workflow,draft};}
  private mapWorkflow(row:any):WorkflowRecord{return{id:row.id,tenantId:row.tenant_id,name:row.name,description:row.description??"",createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString()};}
  private mapDraft(row:any):WorkflowDraft{return{workflowId:row.workflow_id,revision:Number(row.revision),definition:row.definition,contentHash:row.content_hash,updatedBy:row.updated_by??undefined,updatedAt:new Date(row.updated_at).toISOString()};}
  private mapVersion(row:any):WorkflowVersion{return{id:row.id,workflowId:row.workflow_id,versionNumber:Number(row.version_number),definition:row.definition,compiledPlan:row.compiled_plan,contentHash:row.content_hash,releaseNotes:row.release_notes??"",publishedBy:row.published_by??undefined,publishedAt:new Date(row.published_at).toISOString()};}
  async list(tenantId:string,limit=50):Promise<WorkflowRecord[]>{if(this.pool){const result=await this.pool.query(`SELECT * FROM workflows WHERE tenant_id=$1::uuid AND archived_at IS NULL ORDER BY updated_at DESC LIMIT $2`,[tenantId,limit]);return result.rows.map(row=>this.mapWorkflow(row));}return[...this.workflows.values()].filter(item=>item.tenantId===tenantId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,limit);}
  async workflow(tenantId:string,id:string):Promise<WorkflowRecord|undefined>{if(this.pool){const result=await this.pool.query(`SELECT * FROM workflows WHERE id=$1::uuid AND tenant_id=$2::uuid`,[id,tenantId]);return result.rows[0]?this.mapWorkflow(result.rows[0]):undefined;}const item=this.workflows.get(id);return item?.tenantId===tenantId?structuredClone(item):undefined;}
  async draft(tenantId:string,id:string):Promise<WorkflowDraft|undefined>{if(!await this.workflow(tenantId,id))return undefined;if(this.pool){const result=await this.pool.query(`SELECT * FROM workflow_drafts WHERE workflow_id=$1::uuid AND tenant_id=$2::uuid`,[id,tenantId]);return result.rows[0]?this.mapDraft(result.rows[0]):undefined;}const item=this.drafts.get(id);return item?structuredClone(item):undefined;}
  validate(value:unknown):{definition?:WorkflowDefinition;diagnostics:WorkflowDiagnostic[]}{const parsed=workflowDefinitionSchema.safeParse(value);if(!parsed.success)return{diagnostics:parsed.error.issues.map(issue=>({code:"schema_validation",severity:"error",message:issue.message,path:`/${issue.path.join("/")}`}))};return{definition:parsed.data,diagnostics:validateWorkflowGraph(parsed.data)};}
  async updateDraft(tenantId:string,id:string,actorId:string,expectedRevision:number,value:unknown):Promise<WorkflowDraft>{const checked=this.validate(value);if(!checked.definition)throw Object.assign(new Error("Workflow schema validation failed"),{diagnostics:checked.diagnostics});const contentHash=hash(checked.definition);if(this.pool){const result=await this.pool.query(`UPDATE workflow_drafts SET revision=revision+1,definition=$4::jsonb,content_hash=$5,updated_by=$6::uuid,updated_at=now() WHERE workflow_id=$1::uuid AND tenant_id=$2::uuid AND revision=$3 RETURNING *`,[id,tenantId,expectedRevision,JSON.stringify(checked.definition),contentHash,actorId]);if(!result.rows[0])throw Object.assign(new Error("Draft revision conflict"),{code:"draft_revision_conflict"});await this.pool.query(`UPDATE workflows SET name=$3,description=$4,updated_at=now() WHERE id=$1::uuid AND tenant_id=$2::uuid`,[id,tenantId,checked.definition.name,checked.definition.description]);return this.mapDraft(result.rows[0]);}const current=await this.draft(tenantId,id);if(!current||current.revision!==expectedRevision)throw Object.assign(new Error("Draft revision conflict"),{code:"draft_revision_conflict"});const updated={...current,revision:current.revision+1,definition:checked.definition,contentHash,updatedBy:actorId,updatedAt:now()};this.drafts.set(id,updated);const workflow=this.workflows.get(id)!;Object.assign(workflow,{name:checked.definition.name,description:checked.definition.description,updatedAt:updated.updatedAt});return structuredClone(updated);}
  async publish(tenantId:string,id:string,actorId:string,releaseNotes:string,idempotencyKey:string):Promise<WorkflowVersion>{const mapKey=`${tenantId}:${id}:${idempotencyKey}`,cached=this.idempotency.get(mapKey);if(cached)return structuredClone(cached);const draft=await this.draft(tenantId,id);if(!draft)throw new Error("Workflow not found");const diagnostics=validateWorkflowGraph(draft.definition);if(diagnostics.some(item=>item.severity==="error"))throw Object.assign(new Error("Workflow validation failed"),{diagnostics});const compiledPlan=compileWorkflow(draft.definition),versionId=randomUUID();if(this.pool){const result=await this.pool.query(`INSERT INTO workflow_versions(id,tenant_id,workflow_id,version_number,definition,content_hash,compiled_plan,release_notes,published_by,idempotency_key) SELECT $1::uuid,$2::uuid,$3::uuid,COALESCE(max(version_number),0)+1,$4::jsonb,$5,$6::jsonb,$7,$8::uuid,$9 FROM workflow_versions WHERE tenant_id=$2::uuid AND workflow_id=$3::uuid ON CONFLICT(tenant_id,workflow_id,idempotency_key) DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[versionId,tenantId,id,JSON.stringify(draft.definition),draft.contentHash,JSON.stringify(compiledPlan),releaseNotes,actorId,idempotencyKey]);return this.mapVersion(result.rows[0]);}const version:WorkflowVersion={id:versionId,workflowId:id,versionNumber:(this.versions.get(id)?.length??0)+1,definition:draft.definition,compiledPlan,contentHash:draft.contentHash,releaseNotes,publishedBy:actorId,publishedAt:now()};const list=this.versions.get(id)??[];list.push(version);this.versions.set(id,list);this.idempotency.set(mapKey,version);return structuredClone(version);}
  async listVersions(tenantId:string,id:string):Promise<WorkflowVersion[]>{if(!await this.workflow(tenantId,id))return[];if(this.pool){const result=await this.pool.query(`SELECT * FROM workflow_versions WHERE tenant_id=$1::uuid AND workflow_id=$2::uuid ORDER BY version_number DESC`,[tenantId,id]);return result.rows.map(row=>this.mapVersion(row));}return structuredClone((this.versions.get(id)??[]).slice().reverse());}
  async version(tenantId:string,id:string):Promise<WorkflowVersion|undefined>{if(this.pool){const result=await this.pool.query(`SELECT * FROM workflow_versions WHERE tenant_id=$1::uuid AND id=$2::uuid`,[tenantId,id]);return result.rows[0]?this.mapVersion(result.rows[0]):undefined;}for(const [workflowId,versions]of this.versions){if(this.workflows.get(workflowId)?.tenantId===tenantId){const match=versions.find(item=>item.id===id);if(match)return structuredClone(match);}}return undefined;}
  async reserveRun(tenantId:string,workflowVersionId:string,idempotencyKey:string):Promise<{jobId:string;created:boolean}>{const key=`${tenantId}:${workflowVersionId}:${idempotencyKey}`,cached=this.runIdempotency.get(key);if(cached)return{jobId:cached,created:false};const jobId=randomUUID();if(this.pool){const inserted=await this.pool.query(`INSERT INTO workflow_run_requests(tenant_id,workflow_version_id,idempotency_key,job_id) VALUES($1::uuid,$2::uuid,$3,$4::uuid) ON CONFLICT(tenant_id,workflow_version_id,idempotency_key) DO NOTHING RETURNING job_id`,[tenantId,workflowVersionId,idempotencyKey,jobId]);if(inserted.rows[0])return{jobId:inserted.rows[0].job_id,created:true};const prior=await this.pool.query(`SELECT job_id FROM workflow_run_requests WHERE tenant_id=$1::uuid AND workflow_version_id=$2::uuid AND idempotency_key=$3`,[tenantId,workflowVersionId,idempotencyKey]);return{jobId:prior.rows[0].job_id,created:false};}this.runIdempotency.set(key,jobId);return{jobId,created:true};}
  async close():Promise<void>{await this.pool?.end();}
}
